### ISSUE TITLE
Create SFR network from raster DEM using Landlab package

### ISSUE THREAD

**Issue by andyrich** [modflowpy/flopy#1015]
The landlab package is a geomorphology modeling package that could be used to create SFR networks for MODFLOW models using a DEM as the source.  It has a module called the FlowAccumulator that calculates flow accumulation (shown as drainage area in screenshot below) that can then be used as the basis to create an SFR grid. The code can deal with depressions (DepressionFinderAndRouter), has different algorithms to route flows, it assigns upstream/downstream links, and lots of other inputs that SFR needs.

https://landlab.readthedocs.io/en/latest/user_guide/teaching_tutorials.html

![landlab](https://user-images.githubusercontent.com/16653125/98719712-f29c2600-2344-11eb-9361-b73544cae011.png)

**Comment by emorway-usgs** [comment]
@andyrich Does landlab also have something that can take predefined linework (e.g., .shp file) representative of a irrigation system and generate SFR input from that?  For example, irrigation ditch diversions typically follow DEM contours rather than flow perpendicular to them.  To show you what I mean, consider the image below.  Segments labeled "180," "182," "188," "193," & "196" represent the mainstem of a major river, whereas the other displayed segments represent features associated with an irrigation system.  There are numerous diversions (red arrows) and man-made return ditches that may not lend themselves to flow-accumulation algorithms.  Also, there are locations where siphons are used to "cross" natural tributaries without interacting with them (orange arrows).  Do you have anything that would process predefined linework with an under-lying model grid like what I've described/shown?
![canal_network](https://user-images.githubusercontent.com/3236576/98725571-23328e80-234a-11eb-8eff-f436a00b0073.png)

**Comment by andyrich** [comment]
> @andyrich Does landlab also have something that can take predefined linework (e.g., .shp file) representative of a irrigation system and generate SFR input from that? For example, irrigation ditch diversions typically follow DEM contours rather than flow perpendicular to them. To show you what I mean, consider the image below. Segments labeled "180," "182," "188," "193," & "196" represent the mainstem of a major river, whereas the other displayed segments represent features associated with an irrigation system. There are numerous diversions (red arrows) and man-made return ditches that may not lend themselves to flow-accumulation algorithms. Also, there are locations where siphons are used to "cross" natural tributaries without interacting with them (orange arrows). Do you have anything that would process predefined linework with an under-lying model grid like what I've described/shown?
> ![canal_network](https://user-images.githubusercontent.com/3236576/98725571-23328e80-234a-11eb-8eff-f436a00b0073.png)

I don't think that landlab would be directly useful in solving that problem.

**Comment by emorway-usgs** [comment]
> The landlab package is a geomorphology modeling package that could be used to create SFR networks for MODFLOW models using a DEM as the source. It has a module called the FlowAccumulator that calculates flow accumulation (shown as drainage area in screenshot below) that can then be used as the basis to create an SFR grid. The code can deal with depressions (DepressionFinderAndRouter), has different algorithms to route flows, it assigns upstream/downstream links, and lots of other inputs that SFR needs.

Hello @andyrich, do you have an example that relies on landlab as you showed in your first post (of this thread) but also generates SFR input?

**Comment by andyrich** [comment]
Sorry, I do not.

**Comment by jdhughes-usgs** [comment]
@andyrich @jlarsen-usgs and others have developed a flow accumulation tool for GSFLOW (maybe you already know about this). The plan is this base functionality will be available in flopy. Stay tuned. Closing this issue for now.
