### ISSUE TITLE
Handling of unconnected reaches in mf6 sfr package

### ISSUE THREAD

**Issue by aleaf** [modflowpy/flopy#1017]
As of modflow-6 version 6.2, unconnected reaches can be specified in the connectiondata block as just the reach number, with `ncon=0` in the corresponding `packagedata` entry. However when just the reach is specified in the ``connectiondata`` argument to ``ModflowGwfsfr``, the following error results (for an unconnected reach 2):

```
flopy.mf6.mfbase.MFDataException: An error occurred in data element "connectiondata" model "shellmound" package "sfr_0". The error occurred while setting data in the "__init__" method.
Additional Information:
(1) Data line [2] only has 1 entries, minimum number of entries is 2.
(2) Error occurred while adding dataset "connectiondata" to block "connectiondata"
```

Specifying ``[2, None]`` works, but then the sfr input file has
```
2 None
```
for the connectiondata entry, which causes modflow to crash.

**Comment by spaulins-usgs** [comment]
@langevin-usgs I can fix this easily by updating gwf-sfr.dfn and making ic optional in connectiondata.  If I propagate this change to the MF6 dfn this will make ic appear as optional in the documentation.  ic is in a sense optional but not truly optional since whether you specify it is dependent on packagedata.  Is marking it as optional in the dfn acceptable?

**Comment by langevin-usgs** [comment]
@spaulins-usgs, that sounds reasonable to me as long as you explicitly say in the description for ic that it is only optional (and should actually not be specified) if ncon is specified as zero for the reach in the packagedata block.
