### ISSUE TITLE
Does PEST (implemented in FloPy) work with MODFLOW 6 !

### ISSUE THREAD

**Issue by MostafaGomaa93** [modflowpy/flopy#1032]
If not, when it is expected that FloPy will be adapted to include PEST for MODFLOW 6?

**Comment by jtwhite79** [comment]
Not sure about this - I think the org PEST stuff that is in flopy now was a @mnfienen-usgs contribution.  I personally have moved all of my pest world stuff to [pyemu](https://github.com/pypest/pyemu) so that we can keep playing nice. pyemu has routines to write tpl and ins files for generic csv and array files and then make a control file from them (there are also higher-level automated routines in pyemu for mf6 like [this](https://github.com/pypest/pyemu/blob/develop/examples/pstfrom_mf6.ipynb).  Generally, with the flopy ability to write all external files (thanks @spaulins-usgs !) and the modern input structure of mf6, the pest stuff is a lot easier...

Those are just my thoughts - Im open to other ideas...

**Comment by MostafaGomaa93** [comment]
@jtwhite79: what I understand is that pyemu works with dis, so not adapted to disv, Right?

**Comment by jtwhite79** [comment]
The lower level routines in pyemu for building template files instructions and then pest control files are generic - you have tell these routines how and what to make parameters and observations.   But if you wanna take advantage of the automatic setup stuff (like getting a geostatistical prior ensemble) then you are right, the modflow 5 stuff is geared for dis.  But the newer PstFrom functionality should be pretty close to working with disv since it can deal with list style inputs files.  But "close" is not done...
