### ISSUE TITLE
length unit and best way to set spatial reference

### ISSUE THREAD

**Issue by aleaf-usgs** [modflowpy/flopy#104]
Jeremy,
What is the best way to define a spatial reference for a model if it is not described in the namefile header?

For example:

``` python
xll, yll = 649521.5, 5116116.1
yul = yll + 76.2 * 800
m = flopy.modflow.Modflow.load('badriver.nam', model_ws='br_model_files', verbose=True)
m.sr = reference.SpatialReference(delr=m.dis.delr, delc=m.dis.delc, lenuni=2, xul=xll, yul=yul, rotation=0.0, proj4_str="EPSG:26715")
m.sr
Out[28]:
xul:649522, yul:5.17708E+06, rotation:0, proj4_str:EPSG:26715
m.sr.lenuni
Out[31]:
1
```

I'm guessing the lenui argument is where the length units of the reference are defined. But for some reason it remains as 1 even if 2 (meters) is input. `export()` then produces shapefiles with the proper projection, but with the length units still in feet (so the upper left corner is correct, but lower right extends far beyond the model area).

It would also be great to have an option to input lower left corner instead of upper left, as it seems like the location of models is often defined by the lower left corner. This would be especially useful for rotated grids.

**Comment by jtwhite79** [comment]
It gets tricky with having the spatial reference attached to the model but relying on the ``DIS``.  So, once the model is loaded (including ``DIS``), you can set the attributes of the model's sr one-at-a-time like:
```
m = flopy.modflow.Modflow.load('badriver.nam', model_ws='br_model_files', verbose=True)
m.sr.xul = 12345
m.sr.yul = 6789
```
 This is the safest way because  ``__setattr__`` is catching these attribute changes and resets the other ``SpatialReference`` attributes that depend on them.  

Now for some trickery: the actual sr instance is attached to ``DIS``, so if you want to replace the entire sr, you probably need to replace it on the ``DIS`` - model's sr is actually just a view of the ``DIS`` sr attribute. I just added an example of your problem to test_t007 and it passes - I've been messing around in ``SpatialReference`` a little this week - are you using the most recent develop commit?      

FYI - There's a  ``units`` attribute in ``SpatialReference`` to represent the units of the CRS - since, in theory, you could have a model with ``lenuni`` in feet and a CRS in meters.    

I think it would be nice to have the option to specify ``xll`` and ``yll`` - others have asked about that too - we went with upper left to be consistent with PEST.  I don't think it wouldn't be hard to implement, but I think there might be some added complexity with specifying the rotation if you aren't rotating about the upper left corner - a little trig would probably fix that right up...

**Comment by jtwhite79** [comment]
I should mention that the ``units`` attribute is currently only used in the netcdf export, but in theory it could also be used in the shapefile export to scale ``delr`` and ``delc``.
