### ISSUE TITLE
Endpoint and Pathline files can be read (MODPATH 7 create simulation example )

### ISSUE THREAD

**Issue by pjquant** [modflowpy/flopy#1074]
The example code crashes when tries to read endpoint and pathline files:

```
fpth = os.path.join(ws, mpnamf + '.mppth')
p = flopy.utils.PathlineFile(fpth)

fpth = os.path.join(ws, mpnamf + '.mpend')
e = flopy.utils.EndpointFile(fpth)
```
Erro message:
for pathlines:
`ValueError: could not convert string to float: '0.50000000E+00-806464328'`

for endpoint file:

`ValueError: invalid literal for int() with base 10: '0*****'`

I am using:

```
3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
numpy version: 1.19.2
matplotlib version: 3.3.4
flopy version: 3.3.3
```
and:

```
MODPATH Version 7.2.001   
Program compiled Dec 22 2017 11:11:36 with IFORT compiler (ver. 16.0.0)  
```

**Comment by rodrperezi** [comment]
Hey,

which example specifically ? Also, could you take a look to your modpath output files ? It seems that flopy is trying to read the output but it finds those weird values within the files. This indicates that might be an issue related to your modpath simulation rather than flopy itself.

Regards

**Comment by jdhughes-usgs** [comment]
Reopen this issue if it is not resolved.
