### ISSUE TITLE
well package unstructured MODFLOW-USG (node, rate)

### ISSUE THREAD

**Issue by manupy-hub** [modflowpy/flopy#1079]
Hi all,
I was wondering if it is possible to add wells in an unstructured grid in MODFLOW-USG as (node, rate). I was checking the documentation and apparently I can only add wells as [layer, row, col, rate].

Is it not implemented or there is a different way to do it?

Thanks!

**Comment by jdhughes-usgs** [comment]
See https://github.com/modflowpy/flopy/blob/develop/autotest/t506_test.py for an example of how to create a CHD boundary file for MODFLOW-USG.

```python
    chdspd = []
    for x, y, head in [(0, 10, 1.0), (10, 0, 0.0)]:
        ra = g.intersect([(x, y)], "point", 0)
        ic = ra["nodenumber"][0]
        chdspd.append([ic, head, head])
```
where `ic` is the node number. Then the CHD file is made with

```python
chd = flopy.modflow.ModflowChd(m, stress_period_data=chdspd)
```

You would do something similar for the WEL package

Reopen this issue if your issue is not resolved.
