### ISSUE TITLE
slow flopy.plot.PlotMapView.plot_array

### ISSUE THREAD

**Issue by wkitlasten** [modflowpy/flopy#1117]
Updated to flopy version 3.3.4 and existing calls that took seconds are now taking minutes. Admittedly my grid is large, and the method works find for smaller grids, but thought it might be worth mentioning.

A quick example with 10 million cells that takes over 10 minutes to generate the plot (which is longer than the model run and only took a couple seconds with 3.3.3):

```
sim = flopy.mf6.MFSimulation(sim_name='big_grid',exe_name="mf6",
                             version="mf6",sim_ws='big_grid')
tdis = flopy.mf6.ModflowTdis(sim,pname="tdis",time_units="DAYS",
                             nper=1,perioddata=[1.0,1,1.0])

gwf = flopy.mf6.ModflowGwf(sim, modelname='big_grid')
dis = flopy.mf6.ModflowGwfdis(gwf,nlay=1,nrow=1000,ncol=10000,delr=1,delc=1,top=10,botm=0)
pmv=flopy.plot.PlotMapView(modelgrid=gwf.modelgrid)
pmv.plot_array(dis.top.array)
```

**Comment by jlarsen-usgs** [comment]
@wkitlasten 

It looks like the slow down has to do with building patches. I moved everything over to PatchCollections to simplify the plotting code and make it uniform between modelgrid types in version 3.3.4. I'm looking for solutions for redering polygons/polygon collections quickly to speed this up. Thanks for reporting this issue!

**Comment by jlarsen-usgs** [comment]
@wkitlasten 

I found a solution that will work for now to speed up the plotting routines. 1) for structured grids we will revert back to using a `QuadMesh` instance instead of a `PatchCollection`. As you pointed out, `QuadMesh` plots 10 million cells in ~2 seconds, `PatchCollection` was taking ~10 minutes.

For Unstructured and Vertex based modelgrids, I've updated the `PlotMapView` code to use `PathCollection`. This shows quite a bit of spedd improvement over `PatchCollection`. Timings here for 10 million cells are ~35 seconds for `PathCollection` which is a great improvement over `PatchCollection`'s 10 minutes.

I'll be putting in a PR sometime today with these changes.
