### ISSUE TITLE
Is there any plan to add the functionalities of linear feature packages (CLN in USG or Modflow-CFP) ?

### ISSUE THREAD

**Issue by hzhang4** [modflowpy/flopy#1125]
Just wondering if there is already a plan to add the conduit flow processes in Flopy. It seems neither Modflow-CFP nor MFUSG-CLN is supported by Flopy.  
 
Thanks,

**Comment by langevin-usgs** [comment]
We do not have any plans to work on this at the moment.  If someone were to take this on, and submit a PR with accompanying tests and documentation, I think we would be willing to merge it in.

**Comment by hzhang4** [comment]
Hi, 

I have worked on incorporating MFUSG-CLN last couple of weeks. The code is mostly done and have been tested using examples provided with MFUSG 1.5. Besides a new Modflow:ModflowCln class, there are also extensive change to the ModflowBcf and ModflowWel classes to incorporate the additional parameters for mfusg. To work with the wells simulated as CLN nodes, the changes to Package load function in pakbase.py and write_transient function of MfList is also necessary. 

Please let me know what is the best way to merge the changes. The files can be found in the usg-cln repository under my username. 

Hua Zhang

**Comment by langevin-usgs** [comment]
Thank you for your message.  If you think these changes are generally useful and do not have side effects on other working parts of flopy, then we would consider merging them in if you submit a pull request.  Ideally, we would hope that you do not need to make extensive changes to ModflowBcf, ModflowWel, pakbase, MfList and other low-level routines because it is easy to break things.  Also, we require that pull requests contain new autotests to ensure that the capabilities are functioning properly and so that we do not break these capabilities in the future as we maintain flopy.  The autotest folder has examples of what these tests should look like.
