### ISSUE TITLE
Problem with flopy.utils.GridIntersect()

### ISSUE THREAD

**Issue by hwreeves-USGS** [modflowpy/flopy#1153]
I ran into performance problems with flopy.utils.GridIntersect()  when trying to intersect a shapefile with 930 
polygons and a pretty big model grid.  nrow*ncol = 141904.

- setting method to ‘vertex’ and rtree = True: these options lead to a memory error.
- With method=‘structured’ : looping over 930 features is taking a very long time.
- With method =‘vertex’ but rtree = False: lpoping over 930 features
[model_grid_intersect.pdf](https://github.com/modflowpy/flopy/files/6826455/model_grid_intersect.pdf)
 taking very long time!

As shown in the attached pdf, I can get the intersection alright using
either (1) rtree index and then intersect with shapely polygons or (2) geopandas.

I'm not sure if others are already working on this package, but I think it would
be pretty straightforward for me to edit the class to allow users to put in
[model_grid_intersect.pdf](https://github.com/modflowpy/flopy/files/6826466/model_grid_intersect.pdf)

'structured' and rtree=True and then use the rtree index approach for the
intersection.  I'd just need to figure out the right format for the returned
list of cells.  

Let me know if this is of interest or if most users are doing something like 
geopandas outside of flopy so that its not very high priority.

**Comment by dbrakenhoff** [comment]
Hi @hwreeves-USGS,

Thanks for sharing your experience with GridIntersect! 

> - setting method to ‘vertex’ and rtree = True: these options lead to a memory error.

The MemoryError kind of surprises me, but I might be missing something. I've tested GridIntersect with larger grids than you're currently dealing with (500 x 500 grids for example) without any trouble. I do have 32GB RAM so maybe thats hiding the fact that the memory usage is quite high. I'll run some tests to see if I can find anything. Are you using the most recent flopy/shapely releases? 

> - With method=‘structured’ : looping over 930 features is taking a very long time.

Yes, the structured methods are often slower for Polygon intersections for large grids. So I would always recommend using `method='vertex'` and `rtree=True` for those operations even for structured grids. 

> - With method =‘vertex’ but rtree = False: lpoping over 930 features taking very long time!

Yea, doing intersection operations on large grids without the rtree is not a great idea. In that case the list of all gridcells is filtered using a prepared Shapely geometry which can take quite some time. With the rtree, the tree is queried with the bounding box of the shape resulting in a list of gridcells, which is then filtered with that prepared geometry. The intersections are then calculated for the remaining gridcells.

As for your alternative examples, GridIntersect shouldn't be working too differently from your rtree implementation. However,  a difference is that the tree in GridIntersect contains Shapely geometry objects and not just an index and some bounds, which may increase its memory usage? 

I made a notebook with a simple example comparing GridIntersect with the methods you showed. I'm curious whether you're able to run the notebook and what the results are like on your PC?

[intersect_comparison.zip](https://github.com/modflowpy/flopy/files/6831353/intersect_comparison.zip)

There are currently some developments ongoing with rtrees in Shapely2.0/pygeos that might be also be interesting for GridIntersect. But we'll have to wait on the official release first. 

Also, I'm sure there it might be possible to realize better performance (e.g. through an implementation other than shapely or through parallelization), but I think that might add a a lot of complexity and/or dependencies. But if you do find any, I'm still interested to hear about them.

**Comment by jdhughes-usgs** [comment]
@hwreeves-USGS Did this resolve your issue? Reopen the issue if it is not resolved.

**Comment by sannedesmet** [comment]
Hi,

Me and my colleagues encounter the same problem as described by @hwreeves-USGS.
I tried running the notebook, however running led immediately to bad allocation errors  (memory errors) and complete shut down of my computer. I have this problem only with vertex and rtree and I think it is due to the fact that I only have a 16GB RAM. On computers with more RAM this issue did not occur. 

I did some test and it appears that the memory error already occurs when the object Gridintersect is created, this makes it very hard to check the memory usage outside of the original code within flopy. I would be of great help if this problem could be solved or at least a warning would be created to prevent my computer from crashing.

**Comment by dbrakenhoff** [comment]
HI Sanne,

Any chance you can share the intersection you're trying to perform, i.e. the shape and the grid? I'll try to reproduce the issue and see if I can figure out what's going on. Also what version of Shapely are you using?

The fact that it happens when creating the GridIntersect object means it is related to converting the grid to a collection of shapely shapes, or the building of the rtree. The methods `GridIntersect._vtx_grid_to_shape_generator()` and `GridIntersect._rect_grid_to_shape_generator()` convert the grid cells to collections of shapely geometries. Perhaps you can try running the code from these methods separately (replacing `self.mfgrid` with your modelgrid object) to check whether that is the cause of the memory issues?

**Comment by sannedesmet** [comment]
Hi,

I was trying to run your example notebook ([intersect_comparison.zip](https://github.com/modflowpy/flopy/files/6831353/intersect_comparison.zip)) .

I get a Memory Error when running line: 
`t = get_ipython().run_line_magic('timeit', '-o -r 1 -n 1 GridIntersect(sgr, method="vertex", rtree=rtree_bool)')`

I tried running the methods inside of Gridinstersect separately, as you mentioned. Since the example is a structured grid I only tried: 
`GridIntersect._rect_grid_to_shape_generator() `. This line is not a problem, however running: `STRtree(self._get_gridshapes())`, gives me an immediate MemoryError with complete crash of my computer.

**Comment by dbrakenhoff** [comment]
What about running `list(self._get_gridshapes())`? Does that also lead to a memory error?

**Comment by sannedesmet** [comment]
list works fine. I didn't encounter any errors.  I also just found that the MemoryError with STRtree is known: https://github.com/shapely/shapely/issues/1135

**Comment by dbrakenhoff** [comment]
Ah, that explains why I cannot reproduce the issue on Ubuntu.

Can you check if installing the latest version of Shapely=1.8.2 (with GEOS>=3.10) solves the issue?

**Comment by sannedesmet** [comment]
That solved the issue. I don't have a MemoryError anymore.
