### ISSUE TITLE
changes required in hydfmt.f for write_input() to generate .hds file on Arch Linux Intel86_64.

### ISSUE THREAD

**Issue by archgroove** [modflowpy/flopy#124]
I could not write .hds files with write_input() using the example from tutorial1.py. No error was thrown until attempting to read a non-existent .hds file with hds = bf.HeadFile(modelname+'.hds').

Fix: I can now write_input() to .hds files after changing the analogous parameters on Line 98 of hydfmt.f and recompiling. NB. I did this after implementing the fix for Issue #11 (which fixed a problem reading .hds on linux/mac).
FORM='BINARY' --> FORM='UNFORMATTED'
ACCESS='SEQUENTIAL' --> ACCESS='STREAM'

**Comment by langevin-usgs** [comment]
Hi @claireverity, I can't tell from your description if you are having a problem, or if you are reporting how to fix hydfmt so that it works on non-windows operating systems.   Just to be clear, the write_input() method does not create a .hds file.  The .hds file is created by MODFLOW (using run using run_model() or some other method) and Output Control has the proper save settings.

**Comment by cindyzhouc** [comment]
In makefile, use F90= gfortran .
In openspec.inc
change DATA ACCESS/'SEQUENTIAL'/ to DATA ACCESS/'STREAM'/
change DATA FORM/'BINARY'/ to DATA FORM/'UNFORMATTED'/

This solution doesn't work or me for running flopy. I still get error messages
*** ERROR OPENING FILE "tutorial1.hds" ON UNIT    51
       SPECIFIED FILE STATUS: REPLACE
       SPECIFIED FILE FORMAT: BINARY              
       SPECIFIED FILE ACCESS: SEQUENTIAL          
       SPECIFIED FILE ACTION: READWRITE           
  -- STOP EXECUTION (SGWF2BAS7OPEN)

Any suggestions?

**Comment by jdhughes-usgs** [comment]
This is not a flopy issue but a compiler issue.
