### ISSUE TITLE
flopy.mf6.MFSimulation.load fails if lake bathy file stored in different dir

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#1337]
MF6 runs fine, but flopy bombs during load if lake bathy tables are stored in a different dir. For example:

BEGIN TABLES
  2 TAB6 FILEIN lake_bathy_data\lak_bathy_lak_TwU.dat
  ....
Wont work

**Comment by spaulins-usgs** [comment]
@jdhughes-usgs, in your PR "ci: convert from nosetest to pytest" you deleted (commented out) test "test045_lake1ss_table" from t504_test.py.  I would like to add that test back in since it is the only lake tabs test we have.  My PR to fix this bug (#1344) includes adding a modified version of test045_lake1ss_table back into our t504 test suite.  Just checking to see if there was a reason for its removal before adding it back in.
