### ISSUE TITLE
Is there a plan for supporting multi-layer USG?

### ISSUE THREAD

**Issue by collord** [modflowpy/flopy#134]
in mfdisu.py:

"Does not work yet for multi-layer USG models because top and bot cannot
  be u3d instances until u3d is modified to handle multiple u2d instances
  of different size."

**Comment by langevin-usgs** [comment]
This is certainly on the Todo list.  I would really like to see it happen, but just haven't had enough time to implement something that is general.  In the meantime, I have been just putting all my cells into 1 MODFLOW-USG layer, even if I'm actually using multiple layers.  MODFLOW-USG doesn't care, as long as the IVC array is specified correctly so that the program knows how cells are connected.  But really, all this should be redone so that the model mapping and post processing works correctly.  This will take a bit of effort.

**Comment by jdhughes-usgs** [comment]
@langevin-usgs Is this still an issue?
