### ISSUE TITLE
Read drawdown file MODFLOW USG with flopy 

### ISSUE THREAD

**Issue by kdemierres** [modflowpy/flopy#1369]
Hi everybody, 
I'm trying to read the drawdown file (.ddn) of una MODFLOW USG model. I'm using HeadUfile because it is and unstructured model, but I'm not sure if it is right, the code takes a lot of time computing. The Flopy manual doesn't specify if we have to use HeadFile or HeadUFile for MODFLOW USG drawdown file. Do you know what is right? 
Thanks you in advance.

**Comment by cnicol-gwlogic** [comment]
Hi,

If your model is unstructured (i.e. your model has a disu file), use HeadUfile. Some things I can think of that could cause issues:
* Do you have CLNs in your model? If so, if ddn/saturation is being saved to the same ddn file as groundwater node heads, then you will encounter issues. You need to save CLN heads/ddn/saturation to different hds/ddn files if you want to use flopy with your model.
* Is anything else being written to your ddn file? Check the list file for the ddn unit number ("saving XXX to unit YY" at the end of a save stress period).
* precision - is your file double or single precision? You need to specify this to headufile if it is double precision. Flopy should warn you on this if you get it wrong (I think).
* Have you tried reading your file with a PEST utility instead? E.g. usgmod2smp or usgarrdet (see [here](https://s3.amazonaws.com/docs.pesthomepage.org/software/gwutils.zip)). Does it work?
* Failing these, upload your files somewhere and I can try to take a quick look.

Chris.

**Comment by kdemierres** [comment]
Hi Chris, 
I've checked all things except try with a PEST utility because I don't know how to do it. But all other things are ok. If you can take a look, I uploaded the files [here](https://drive.google.com/drive/folders/1eKpr1BYvApoRkUWv785Yoy-aiubAHU9n?usp=sharing).
Thanks you very much!

**Comment by cnicol-gwlogic** [comment]
The problem is you have no saturation data in your ddn file. I guess flopy should detect this and report an error, but it is not. 

None of the below is a flopy issue.

You can confirm the contents of your ddn file has saturations in it by:
* checking the modflow list file like I suggested earlier (there is no mention of the word "saturation" (nor "richards"))
* or running usgarrdet from the pest gw utilities - this shows only drawdownu arrays are in your ddn file. I've included an example below to show you how to do this - it is dead easy.
* try extracting drawdownu from your ddn file instead (it works in seconds). That would be a giveaway that saturations are not in there.

Despite this, your model does not appear to be simulating unsaturated zone flow (I think). Try replacing your LAYCON = 4 variables to 5 instead. I've done this edit in the version of your model files (LPF line 3) [here](https://groundwaterlogiccom-my.sharepoint.com/:u:/g/personal/chris_nicol_groundwaterlogic_com/EYjxmodtHcJIrdjfMFhEBEsBEQnv0LvJAIiUue00RMEvvw?e=HCaP0l), but I can't test run your model as I don't have your initial heads file. I think what's happening is that deapite you having the "RICHARDS" keyword in your BAS, you have the bottom most layer set to laytyp 0 (confined / contstant T/S) - so maybe usg skips richards calcs unless you apply layer-by-layer laytyp 5 to the layers you want richards calcs done (read the manual for info on this, but no it is not crystal clear to me either).

In that linked zip above, I've also included a batch file for running usgarrdet, and a little script to pull the saturations (or drawdowns) from the ddn file.

**Comment by jdhughes-usgs** [comment]
@cnicol-gwlogic can this issue be closed?

**Comment by cnicol-gwlogic** [comment]
@jdhughes-usgs yep go for it
