### ISSUE TITLE
How to access water content with utils.binaryfile

### ISSUE THREAD

**Issue by MDMascini** [modflowpy/flopy#1375]
Hi there! 

Im trying to get the water content of the cells of my ground water flow model with the UZF package. I have specified a name for the binary output file in the UZF package as follows: 

`uzf = flopy.mf6.ModflowGwfuzf(
    gwf,
    pname="UZF-1",
    nuzfcells=nuzfcells,
    packagedata=packagedata,
    perioddata=uzf_perioddata,
    save_flows=True,
    wc_filerecord = "{}.bin".format(name)      
)`

And I see that a binary file is made in the directory. Is there a way to use the utils.binaryfile function of Flopy to easily read the data similar to reading the head and cell by cell budget files?

Thanks in advance!

**Comment by MDMascini** [comment]
This worked perfectly, thank you!

**Comment by cnicol-gwlogic** [comment]
No I don't know sorry. That would be one for sorab.

**Comment by langevin-usgs** [comment]
@emorway-usgs can you explain why this is the case.

**Comment by emorway-usgs** [comment]
@MDMascini, I agree, this is not the expected behavior.  There was a [pull request on the MF6 repo](https://github.com/MODFLOW-USGS/modflow6/pull/730) aimed at fixing this very thing.  I'll rework that PR and spruce up the testing using the autotest that was included with that PR.  It might be best to close this FloPy issue and reopen as a MF6 issue.

**Comment by MDMascini** [comment]
Thanks for your response!

**Comment by geohang** [comment]
> Will something like the following help out, where `name` is the base name of the model, `*.uzf.bin` is the file extension of the binary output, and `ws` is a path to where the UZF output file resides:
> 
> ```
> fname = os.path.join(ws, "{}.uzf.bin".format(name))
> wobj = flopy.utils.HeadFile(fname, text="WATER-CONTENT")
> wc = wobj.get_alldata()
> ```

Hi, I have a follow-up question. It seems in this way, we can only got the water content information but we cannot got the depth and regarding water content information. Do you know how to get the depth-water content? Thank you!

**Comment by emorway-usgs** [comment]
@ geohang, In order to retrieve the water content for a specific depth, you can use the observation options that are available with the UZF package.  

For example, in the MODFLOW6 repo's autotests folder, there [is a script](https://github.com/MODFLOW-USGS/modflow6/blob/develop/autotest/test_gwf_uzf04.py) titled `test_gwf_uzf04.py`, if you run that script it creates a UZF observation file that demonstrates how to do the kind of thing you're asking for.  

I'm attaching both the UZF input file and UZF Obs input file generated by that script that should provide a relatively simple example for you to mimic.  If you have questions about what's in the UZF Obs input file, the MF6io.pdf document lays it out nicely:

![tab19](https://user-images.githubusercontent.com/3236576/190944289-31fb7a5d-42bd-4de2-b56c-46bf12ab4220.png)

**Comment by geohang** [comment]
That's very helpful. Thank you so much!
