### ISSUE TITLE
external filename getting reset/changed

### ISSUE THREAD

**Issue by briochh** [modflowpy/flopy#1534]
When updating some package data using `set_data()`, data storage gets set to `internal` even if the original was `external`. This can cause issues when the user wants to used specified external file names (or locations) as the call to `set_all_data_external()` stomps on the `fname` that is stored on the object and resets it to a default. 

For example,
if gwf.dis is instantiated with:
`botm=[{"filename": f"botm_{k.}txt", "data": ar} for k, ar in enumerate(array)]`
but then the array is modified through:
`gwf.dis.botm.set_data(newdata)` 
The data storage is reset to `internal`, and calling `gwf.dis.set_all_data_external()` overwrites the value of `fname`, for e.g. `gwf.dis.botm[0].fname` gets set to '{model_name}.dis_botm_layer1.txt'

This is possibly at the intersection of two fairly minor issues
1. resetting files to internal when just updating the array data -- can we just retain the "external" status?
2. ignoring defined fnames for internal files when setting to external -- if `fname` is already on the object can that be accomodated when setting external?

It can cause problems if other processes are expecting to interact with the model data files.

**Comment by spaulins-usgs** [comment]
@briochh As you pointed out, the internal status is getting reset because the second call to set_data is setting data without any external file information, and set_data interprets this as a request to set internal data.  

Rather than changing the default way set_data functions, which could break people's existing code, how about I add an optional parameter, "preserve_data_location", to the set_data methods?  This parameter will default to False (existing flopy behavior), but when set to true set_data will not override the existing data location.

Another possibility is that I could add an optional parameter to get_data, "get_data_location" which returns the data location information with the data.  For your botm example it would return a dictionary for each file in the following format:

{"filename": "botm_1", "data": data}

This would allow you to call get_data with get_data_location set to True, modify the data within the dictionary returned, and then call set_data passing in the dictionary, which includes the existing data locations.

If you have a preference on which solution gets implemented, or have another idea, feel free to let me know what you think.

**Comment by langevin-usgs** [comment]
@spaulins-usgs, the following code is from flopy readthedocs and shows an example of a more sophisticated set_data() call for a three layer K22 array:

```
a0 = {"factor": 0.5, "iprn": 1, "data": 100 * np.ones((10, 10))}
a1 = 50
a2 = {"factor": 1.0, "iprn": 14, "data": 30 * np.ones((10, 10))}
npf.k22.set_data([a0, a1, a2])
```

Presumably, the `a0` and `a2` dictionaries could have file information as well.  I guess a question is how does someone get back all of this information, make a change, and then set all of this information again?  It seems like a fix for filenames is not comprehensive and doesn't handle factor, iprn, and other data-related entries.

**Comment by spaulins-usgs** [comment]
@langevin-usgs, currently flopy would require the user to directly access some of the underlying data objects to get at the metadata information (factor, iprn, filename, binary), which is not an ideal solution.  Therefore, I will add an easy way for users to get at that information.

Possible solution: Expand on the "get_data_location" idea I mention above to get all data and metadata. This could be done by adding a new method to the data (MFDataArray, MFDataList) objects, "get_data_metadata", that returns a list of all data and metadata.  If there is associated metadata (factor, iprn, filename, binary) that data/metadata is returned in a dictionary. This is the same format passed to set_data in your example above.

**Comment by briochh** [comment]
Hi @spaulins-usgs,
Generally, I think being able to more easily access some of that metadata that is lodged deep in the flopy object would be really helpful. @langevin-usgs is right, we can pass "filename" in the set data dict (not sure aboth the other entries like factor etc) but accessing this information from the flopy object is a bit messy (it may be dependent on which level, if at all, the "fname" attribute is attched to the object).

**Comment by jtwhite79** [comment]
Same here - I've been wanting to make some inputs binary external but other ascii external and others still constants. So some intuitive fine-grained control would sweet az...

**Comment by spaulins-usgs** [comment]
@briochh, I have discussed this with @langevin-usgs and we agreed on the following, hopefully more intuitive, implementation.  

* Keep the existing get_data method and make some modifications to the set_data method
	* The existing get_data method continues to retrieve just the data 
	* The existing set_data method will be changed so that it sets the data without modifying any metadata (filename, iprn, ... remains unchanged)
		* Though if metadata is passed into to the set_data method it will automatically overwrite all metadata, as it currently does.
* Add two new methods, get_record and set_record
	* The new "get_record" method retrieves data with metadata in the same format that you can currently set data with metadata.  In @langevin-usgs's example above get_record would return a list containing the data and metadata from each layer:


    [{"factor": 0.5, "iprn": 1, "data": ndarray(...)}, 
      50,
       {"factor": 1.0, "iprn": 14, "data": ndarray(...)}	
    ]

	* The new "set_record" method sets data with metadata.  This will allow the flopy user to call get_record to get the data with metadata, modify data and/or metadata in the record (eg. change the value of one of the factors or iprns), and then set_record to set the modified data and metadata.
	
I welcome any feedback on this change before I start implementing it.  I believe it will solve this issue with a reasonably intuitive interface, though if you can think of a better or more intuitive way to do this let me know.

@jtwhite79, flopy currently supports making some inputs binary external but others ascii external and others constants.  There are some similar examples in the following tutorial:

https://flopy.readthedocs.io/en/latest/_notebooks/tutorial08_mf6_data.html

Feel free to message me if you have any ideas on how to make this more intuitive.

**Comment by langevin-usgs** [comment]
@spaulins-usgs, one thing I might question in this proposed solution is having get_record() return a list and set_record() take a list as the argument.  It seems like using a dictionary would provide the most flexibility and extensibility.  We've been talking about the grid data arrays so far in this issue, but perhaps this get_record/set_record has broader usage, in which case a list might cause problems if we wanted to be general for other MFdata types.  We should think about what a dictionary representation might be.

```
record_dict = {
    "layer 1": {"factor": 0.5, "iprn": 1, "data": ndarray(...)},
    "layer 2": {"data": 50},
    "layer 3": {"factor": 1.0, "iprn": 14, "data": ndarray(...)},
}
```

I'm not fond of the "layer 1" key naming, so maybe there is something better, and I don't know how any of this fits with the underlying data structures of flopy for mf6, so I understand if further deliberation is required.

**Comment by spaulins-usgs** [comment]
@langevin-usgs, first regarding the key naming, we already have a key numbering convention for stress period data and I think we should be consistent with that.  For stress period data the key is an integer value of the zero-based stress period.  For example,

    rch_period = {0: np.zeros((10, 10), np.float), 
	              2: np.ones((10, 10), np.float)
    }

We should therefore make layer keys zero-based layer numbers to make them consistent with stress period keys:

    starting_head = {
	    0: {"factor": 1.0, "iprn": 1, "data": np.zeroes((10, 10), np.float}
	    1: {"data": 22.0}
    }

Using a dictionary for the layers does not fit perfectly with the underlying data structure, but I can make it work (layers are currently stored in a list).

Since the solutions we are discussing do need to work with the underlying data structures, for clarity I provide a simplified description the underlying data structures below.

Stress period array data is stored in a MFTransientArray object.  For example, the RCHA's stress_period_data is a MFTransientArray:

    rch.stress_period_data

Other array data is stored in a MFArray object.  For example, the IC package's strt is a MFArray:

    ic.strt

MFTransientArray stores all data in dictionary {stress_period_number: DataStorage object}.

MFArray stores all data in a single DataStorage object.

DataStorage contains either a single LayerStorage object (non-layered data) or a list of LayerStorage objects (layered data).  Layered data is data broken up by layer, while non-layered data is either data not broken up by layer or data not containing layers at all.

LayerStorage contains the data along with any associated metadata (external file name, factor, iprn, binary flag, ...).  LayerStorage either stores data for a single layer (layered data) or for all layers (non-layered data).

**Comment by spaulins-usgs** [comment]
@briochh the set_data issue is now fixed.  set_data no longer resets factor/iprn/filename/binary unless you supply that information.  Also, there are now get_record and set_record methods that return and set the data along with the factor/iprn/filename/binary information in a dictionary.   See this updated tutorial for examples of how to use get_record and set_record:

https://github.com/modflowpy/flopy/blob/develop/examples/Tutorials/modflow6data/tutorial08_mf6_data.py

**Comment by briochh** [comment]
Thanks @spaulins-usgs, great work. I'll see how I go with these updated methods.
