### ISSUE TITLE
bug: Importing USG model 

### ISSUE THREAD

**Issue by oscarfasanchez** [modflowpy/flopy#1661]
**Describe the bug**
Hello, 
I'm trying to load a Modflow Usg(1.4) model but in the process I got and error with DRN, Thanks in advance for any help.
The error looks like this:
```
loading oc package file...
Adding SNT094.HDS (unit=30) to the output list.
Adding SNT094.ddn (unit=52) to the output list.
adding Package:  OC
   OC   package load...success
loading drn package file...
   loading <class 'flopy.modflow.mfdrn.ModflowDrn'> for kper     1
  implicit static instance for parameter 8258
Traceback (most recent call last):

  File "D:\OneDrive - UNIVERSIDAD INDUSTRIAL DE SANTANDER\Trabajo\geomatica\Diplomado\Proyectos\Rafael_Angie\model.py", line 15, in <module>
    ml = flopy.mfusg.MfUsg.load(

  File "C:\Users\Oscar\.conda\envs\pest_flopy36\lib\site-packages\flopy\mfusg\mfusg.py", line 263, in load
    files_successfully_loaded, files_not_loaded = cls._load_packages(

  File "C:\Users\Oscar\.conda\envs\pest_flopy36\lib\site-packages\flopy\mfusg\mfusg.py", line 342, in _load_packages
    ) = cls._load_ext_unit_dict_paks(

  File "C:\Users\Oscar\.conda\envs\pest_flopy36\lib\site-packages\flopy\mfusg\mfusg.py", line 414, in _load_ext_unit_dict_paks
    cls._ext_unit_d_load(model, ext_unit_dict, item)

  File "C:\Users\Oscar\.conda\envs\pest_flopy36\lib\site-packages\flopy\mfusg\mfusg.py", line 459, in _ext_unit_d_load
    ext_unit_d_item.package.load(

  File "C:\Users\Oscar\.conda\envs\pest_flopy36\lib\site-packages\flopy\modflow\mfdrn.py", line 314, in load
    return Package.load(

  File "C:\Users\Oscar\.conda\envs\pest_flopy36\lib\site-packages\flopy\pakbase.py", line 1103, in load
    par_dict, current_dict = pak_parms.get(pname)

UnboundLocalError: local variable 'pak_parms' referenced before assignment
```

**To Reproduce**
Link to my model.

https://correouisedu-my.sharepoint.com/:f:/g/personal/oscar_sanchez2_correo_uis_edu_co/Em6kVx0vl7xFngMaCrnxzQgB4esFV4Zwh9rzh1KEoUJ-8g?e=iuuJIs

I Ran:
```python
import flopy
import os

model_ws = os.path.join("MODFLOW", "work")
ml = flopy.mfusg.MfUsg.load(
    "SNT094.nam",
    model_ws=model_ws,
    verbose=True,
    check=True,
    exe_name="mfusg.exe",
    version="mfusg",
    )
```

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Browser : CHROME(but I used Spyder)
 - Version: flopy 3.6. , modflow USG 1.4

**Comment by cnicol-gwlogic** [comment]
Hi @oscarfasanchez ,

I think the problem is your ITMP NP headers per stress period. You have ITMP 8258, and NP 50 in stress period 1 for example. NP is the number of named parameters per stress period, but to activate named parameters, on line 1 of your DRN file you would have to have: PARAMETER NPDRN MXL, and then follow that up with the list of named parameters etc (see the mfusg manual). I think the "50" bit (NP) in your case is an input error (it looks like a misplaced/repeated IDRNCB variable to me). 

So this is not really a bug. Anyway, I've cleaned up pakbase a little (changed the way flopy checks if it needs to read NP at all - in your case it doesn't), and your model will now load. I'm just running tests now, and will submit a PR shortly. Once/if accepted, you can reinstall the flopy develop branch to get around your issue; alternatively, fix those stress period header lines in your DRN file.

Side note: TVM is not supported in flopy yet (very few usg-transport options/packages are) - so it will not be loaded in your case.
