### ISSUE TITLE
feature: broader path-like support

### ISSUE THREAD

**Issue by w-bonelli** [modflowpy/flopy#1729]
**Is your feature request related to a problem? Please describe.**
FloPy currently expects strings for some path parameters (files/dirs to read from or write to, etc). #1712 recently added support for `pathlib.Path` to some internals, allowing [path-like](https://docs.python.org/3/glossary.html#term-path-like-object) objects to be passed e.g. to `MFSimulation`'s ctor.

**Describe the solution you'd like**
Extending path-like support to all user-facing APIs would be convenient for use with modern `pathlib.Path`, removing the need to wrap with `str(...)`, without breaking existing string usages. Type hint `Union[str, os.PathLike]` could be used in the spirit of [PEP 519](https://peps.python.org/pep-0519/#provide-specific-type-hinting-support) &mdash; further SO discussions [here](https://stackoverflow.com/questions/53418046/how-do-i-type-hint-a-filename-in-a-function) and [here](https://stackoverflow.com/questions/58541722/what-is-the-correct-way-in-python-to-annotate-a-path-with-type-hints). In many cases `Path`/path-like are already implicitly supported and docstrings could just be updated, but this is not universally true and some refactoring would be needed.

**Comment by mwtoews** [comment]
Thanks for raising this. I've been slowly working on this since October 2022, e.g. #1583, #1603. With some of the previous refactoring, I've generally found path manipulation with [`pathlib`](https://docs.python.org/3/library/pathlib.html) to be simpler and easier to read than [`os.path`](https://docs.python.org/3/library/os.path.html).

Some general tips:

- Refer to the handy [table of comparison](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module) between `pathlib` and `os` module functions
- Docstrings that have (e.g.) "file_name : str" should be changed to "file_name : str or PathLike"
- If parameter checks are done with the file/path variable, use e.g. `if isinstance(file_name, os.PathLike)`, because there are other path-like classes e.g. [`path`](https://github.com/jaraco/path)
- Update tests to that use refactored functions that use both str and PathLike names, to maintain coverage/support for both

**Comment by w-bonelli** [comment]
Closed by #1730. Some notebooks and tests still use strings instead of paths, but maybe not a terrible idea to keep it that way to exercise both options
