### ISSUE TITLE
Nocross term not recognized

### ISSUE THREAD

**Issue by ebake310** [modflowpy/flopy#1776]
I am trying to activate the NOCROSS command in the dispersion package of Flopy (I am running MODFLOW NWT and MT3D-USGS) but I am getting an error saying 'NOCROSS' is an unrecognized kwarg. Under the version 3.2.6 updates it states that 'DSP will support the use of keyword NOCROSS'. I have tried NOCROSS=True, NOCROSS=0, NOCROSS=1, nocross=True, etc. Does Flopy actually not recognize 'NOCROSS' or is there a different way the keyword should be written? If Flopy does not recognize NOCROSS, how/where should it be manually added to the mt3d .dsp file?

**Comment by emorway-usgs** [comment]
Hello @ebake310, thanks for pointing this omission out, it is somewhat surprising that this hasn't been caught before now.  #1778 should provide the support you're seeking.

**Comment by emorway-usgs** [comment]
@ebake310, if your python environment is using a clone of the FloPy repository located on your local machine, you should be able to pull on develop to get the fix.  Otherwise, the fix will be available with the next release of FloPy.  Because you're using MT3D-USGS in your work, you will want to amend the instantiation of the MT3D model with the `version` argument if it's not already there:

flopy.mt3d.Mt3dms(..., version='mt3d-usgs')

**Comment by ebake310** [comment]
Thank you!
