### ISSUE TITLE
MNW2 truncates discharge rates too early

### ISSUE THREAD

**Issue by dtbaumann** [modflowpy/flopy#179]
Line 499 of mfmnw2.py 

    def _write_2(self, f_mnw, float_format='{:.2f}', indent=12):

truncates discharge rates at 10 L/s if units are m and seconds. This should probably be extended to

    def _write_2(self, f_mnw, float_format='{:.4f}', indent=12):

Thanks and take care

**Comment by aleaf** [comment]
Hi, thanks for raising the issue. Note that the float_format can be set when writing the MNW package by itself:
```
mnw.write_file(float_format='{:.4f}')
```
but this is a pain because there is no way to specify `float_format` when writing files at the model level. I [changed the default for MNW2](https://github.com/modflowpy/flopy/pull/180) to `float_format='{ :15.7E}'`, which is consistent with how other boundary condition packages are written (through the MfList object).
