### ISSUE TITLE
Boundary condition dtype not loaded with auxiliary variables

### ISSUE THREAD

**Issue by JoerivanEngelen** [modflowpy/flopy#183]
I am trying to write a generic "continue model" script that loads and continues a model from the last written output (after for example a computer crash). 

Something I encountered: 
When the model has auxiliary variables added to its boundary condition, I could not find a way to trace back the np.dtype the boundary condition was written with. 

Say the dtype  I originally used is:
`ghb_dtype = np.dtype([('k', '<i4'), ('i', '<i4'), ('j', '<i4'), ('bhead', '<f4'), ('cond', '<f4'), ('zghb', '<f4')])`

If I then do:
`mswt = flopy.seawat.Seawat.load("C:\path\to\model"))`
`print(mswt.ghb.dtype)`

It just prints the default dtype
> dtype([('k', '<i4'), ('i', '<i4'), ('j', '<i4'), ('bhead', '<f4'), ('cond', '<f4')])

Is there a way to retrieve the original dtype?

**Comment by JoerivanEngelen** [comment]
On a similar note: When I try to load an RCT package with multiple species, it only loads the first species.

**Comment by langevin-usgs** [comment]
@JoerivanEngelen could you prepare a small example of your problem, zip it up, and then paste it into this issue?  I'd be happy to take a look, and having your example would make it easier for me.

**Comment by JoerivanEngelen** [comment]
Done for the original problem, will make another one for the RCT multispecies.

[issue_183_aux.zip](https://github.com/modflowpy/flopy/files/770492/issue_183_aux.zip)

**Comment by JoerivanEngelen** [comment]
Woops, I could not reproduce the RCT problems I had. That is probably a mistake on my side. I could, however, reproduce the problem with aux variables, see previous comment.

**Comment by langevin-usgs** [comment]
I finally had a chance to look at this, @JoerivanEngelen.  The problem is relatively simple, and is likely due to our minimal documentation on aux variables (aux variables are briefly mentioned in this [notebook](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_modflow_boundaries.ipynb)).  To use auxiliary variables, you need to specify them in the options argument.  So in your case, you just need to change the GHB constructor from:

```
ghb = flopy.modflow.ModflowGhb(mswt_in, stress_period_data=ghb_data_in, 
                               dtype=ghb_dtype_in, ipakcb=53,
                               options = [1])
```
to:

```
ghb = flopy.modflow.ModflowGhb(mswt_in, stress_period_data=ghb_data_in, 
                               dtype=ghb_dtype_in, ipakcb=53,
                               options = [1, 'aux zghb'])
```

When you do this, the auxiliary variable is created properly, and is then preserved when loaded.  

Note that adding 'aux zghb' to the options tells ModflowGhb to expect zghb in the dtype.   We could make flopy smarter and do this on its own based on dtype, but I suppose it is possible that someone might want these extra columns in the input file, but not actually want them to behave like auxiliary variables in MODFLOW (unlikely though, I agree).

**Comment by flydream0428** [comment]
When a model is already built, how can I load the model correctly with auxiliary variables in multiple packages?
