### ISSUE TITLE
Problem when reading UCN file created with SEAWAT

### ISSUE THREAD

**Issue by iaborsi** [modflowpy/flopy#203]
Hi,
I've successuflly run a model for seawat, using FloPy.
However, when reading the binary UCN file to visualize the solution, this is read not correctly. I've noticed this, beacuse reading the same file with ModelMuse the solution is well displayed.
Just for information, I point out that:
- reading UCN created for MT3D models gives to me no problem: I've checked and FloPy and ModelMuse read those files in the same way.
- This problem does not appear when I read UCN created for "simple" seawat problem (like the test problem that I reprodueced from the SEAWAT User Manual)
- My guess is that (maybe) the problem arises from the presence of "no data" value (1e+30) in the binary file.
Did you experience any similar problem? 
Any help will be appreciated.
Thanks a lot in advance.

**Comment by langevin-usgs** [comment]
Hi @iaborsi, I don't know what the problem is.  The binary readers have been working well for us.  How do the concentrations that you read from Flopy compare to the concentrations that are written to the SEAWAT list file?  They should be the same.

**Comment by iaborsi** [comment]
Hi,
I guess I found the problem. I'm reading UCN file using the method ucnobj.get_data(kstpkper = (kts, kper)), where ucnoobj is the UcnFile object.
I was assuming that it returns the solution at time corresponding to flow model stress period and time step. While it seems to me that the kts (index of time step) refers to transport time step.
For instance: I have a steady state model (1 stress period 1 time step, in the MODFLOW solution). In Seawat it corresponds to 66 transport time steps. So, when reading ucnobj.get_data(kstpkper = (0, 0)) I was assuming to read the FINAL solution (corresponding to 66th transport step), while it seems that I'm reading the first transport step instead. That's why FloPy solution looks different from ModelMuse's one.
Am I correct? 
Thanks a lot in advance,
Iacopo

**Comment by langevin-usgs** [comment]
@iaborsi, you are right in that it is probably better to use the totim keyword.  If you use the get_kstpkper() method, then that should return a list of MODFLOW time step and stress period tuples, but the problem is that there can be multiple transport time steps for a single (kstp, kper) combination.  I would read the UCN file with something like:

```
times = ucnobj.get_times()
for t in times:
    conc = ucnobj.get_data(totim=t)
```
The problem here is that you can't get at the transport time step number (NTRANS), but I don't think that your transpTime variable is actually the transport time step used in the model.  It is rather the consecutive record number within the specified kstp, kper.  You could get the actual transport time step number, but it would require looking into ucnobj.recordarray, which is probably more than you want to do.
