### ISSUE TITLE
Relocate shapefile writer?

### ISSUE THREAD

**Issue by langevin-usgs** [modflowpy/flopy#21]
Jeremy, I like the new shapefile writer.  It looks great.  The ability to add attributes is really slick.  I'm wondering, though, if we shouldn't create a new 'export' submodule, and put it in there instead.  That way we can plan for "to VTK", "to_NetCDF", and anything else we want to support.  I know the map object has those rotated and offset coordinates, but maybe we need to generalize that somehow?

**Comment by apryet** [comment]
FYI, I have developed a bunch of functions to interact with grids in [Qgridder](https://github.com/apryet/Qgridder/wiki/Example-of-interaction-with-Flopy-and-Modflow), a Quantum GIS plugin. I am currently re-writing Qgridder so as to fit PEP8 standards before it is made available in the official Qgis plugin repository. 

The use of Flopy3 from QGIS seems to me really advantageous and I would be happy to collaborate with you and have your feedback about it. Thanks !

**Comment by jtwhite79** [comment]
Chris - That was a quick hack yesterday because I needed that shapefile - very shortsighted.  I think we do need to generalize the spatial components more - that would open up a lot of functionality for things like a generalized exporter,  the PEST utilities (geostatistics mostly), as well as better interaction with codes like Qgridder.  

Just some more shortsighted thoughts: How about a spatial info class that we can attach as an optional attribute to the discretization package?  I think it makes sense to be part of ```DIS```

Alexandre - Qgridder looks pretty cool and some stronger bindings between flopy and qgis would really help me (and others).  Do you have any thoughts about generalizing the spatial info part of ```ModelMap```?

**Comment by langevin-usgs** [comment]
Export submodule exists now.  Closing.
