### ISSUE TITLE
Implement __repr__ method for model and package classes

### ISSUE THREAD

**Issue by tomvansteijn** [modflowpy/flopy#220]
At the moment the model and package classes do not have a repr method defined. Which means they do not provide an informative string when using print().

Debugging would be easier when this method were implemented.

**Comment by langevin-usgs** [comment]
So I spent some time looking into this yesterday during a long plane trip.  This does seem like it would be helpful, but I think we should establish a protocol and agree on some behavior.  There is a lot of discussion about this topic online (see https://stackoverflow.com/questions/1436703/difference-between-str-and-repr-in-python, for example).  My thinking is that we should try and implement both __str__ and __repr__ functionality.  What you are requesting here for debugging purposes is probably better thought of as __str__ functionality.  The challenge will be to get this implemented for our base objects (such as util2d, transient2d, etc.).

So I looked into implementing Util2d repr and str methods and concluded that we should establish how we want them to behave.

For __repr__, I think we should aspire to achieve u2d == eval(repr(u2d)), at least for very small arrays.  So for example this would be ideal:

```
ml = flopy.modflow.Modflow()
u2d = flopy.utils.Util2d(ml, (2, 2), np.float32, 10., 'test')
print(repr(u2d))

gives:

  Util2d(model=ml, shape=(2, 2), dtype='numpy.float32', value=array([[ 10.,  10.], [ 10.,  10.]]))
```

For the str implementation, this is where we could produce something more useful for the user.  I'm not sure how we want to do this.  I implemented something quick and easy and came up with this behavior:

```
print(str(u2d))

gives

Util2D
  name: test
  _Util2d__value_built: None
  _Util2d__value: 10.0
  iprn: -1
  cnstnt: 1.0
  _how: constant
  _format: ArrayFormat: npl:2,format:E,width:15,decimal6,isfree:False,isbinary:False
  shape: (2, 2)
  _acceptable_hows: ['constant', 'internal', 'external', 'openclose']
  locat: None
  dtype: <class 'numpy.float32'>
  model: MODFLOW 0 layer(s), 0 row(s), 0 column(s), 0 stress period(s)
  _ext_filename: test.ref
  ext_filename: None
```

But maybe it would be better to boil this down, perhaps into something like a simple summary string that depends on how the array is represented in the object:

* array (shp) CONSTANT value
* array (shp) INTERNAL MEAN:mean MIN:min MAX:max format
* array (shp) EXTERNAL filename MEAN:mean MIN:min MAX:max format

I think the repr and str behavior for packages may become clearer as we iron out the details for the lower level objects, because then we can call the repr and str functions for lower level objects as we build the repr and str behavior for the higher level objects.  

In looking into this, it did become clear to me that we could benefit from putting some thought into this.  I would say that the behavior right now for a model is pretty bad:

```
ml = flopy.modflow.Modflow()
print(ml)

gives:

MODFLOW 0 layer(s), 0 row(s), 0 column(s), 0 stress period(s)
```

It would be nice to have print(ml) return informative information about the model, which packages are being used, etc.  Ideally repr(ml) would be enough to reconstruct the entire model from the returned string, but the way we've structured flopy, I'm not sure that is reasonable.

I think we also are returning docstrings in some cases, but these should probably be returned from help() instead.

**Comment by tomvansteijn** [comment]
Thanks. Perhaps a mixin class could be interesting for this purpose, see for example [https://github.com/alexprengere/reprmixin](url). With a mixin we can efficiently add this functionality to each class. Will look at your response more carefully later.

**Comment by tomvansteijn** [comment]
Could try to implement the repr method for some classes. I agree eval(repr(object)) ideally returns a replication of the object. With a mixin class the repr method is implemented consistently accross objects (corrected the link above). Instead of using all attributes it is perhaps more efficient to include only those which are arguments of the objects __init__ method. However then the replication might not be exact, if attributes are introduced outside of the __init__ method. On the other hand should anybody use eval(repr(object)) in actual code? 

As for the str method, perhaps I need more familiarity with the objects. I think it would be useful the add the model name, workspace and package list to the current listing of layers, rows, columns and stress period.

**Comment by bdestombe** [comment]
Hi,
An implementation of repr, with u2d == eval(repr(u2d)), would be very useful. I have been working on that for quite some time now, with a somewhat different goal. Maybe parts of it might help for the repr implementation.

https://github.com/bdestombe/flopymetascript


Ciao,
Bas

**Comment by jdhughes-usgs** [comment]
@langevin-usgs can this issue be closed?

**Comment by langevin-usgs** [comment]
We have some of this for the newer MODFLOW 6 classes, but not the mf2005-based classes.  Going to close this for now.  If anyone is interested in taking this on, feel free to reopen.
