### ISSUE TITLE
numpy recarray issues

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#282]
So I'm using the latest numpy from miniconda and there are some big changes to recarrays.  For instance, the ``numpy.core.records.fromrecords()`` will no longer accept a structure array - we have been passing structured arrays this constructor for a while.  Also, the recarray dtype ``desc`` attribute now has a ('','|V') leading entry, which appears to be a raw data (void) entry? This is tripping the format builders.  I've tried to patch a few these to keep pyemu's test passing, but I suspect there are more out there...can we just use pandas now?

**Comment by jdhughes-usgs** [comment]
I suspect replacing recarrays with pandas would just replace one dependency with another. It seems reasonable to expect that pandas would change something in its base functionality that would cause a similar issue for us in the future. 

Could you mock up how pandas would replace recarrays in MFlist for reading and writing boundary data?

**Comment by jtwhite79** [comment]
I'm sure pandas will continue changing in the future, but 90% of what we are doing with recarrays is casting and I/O, which, I would estimate, is an auxiliary/secondary function of recarrys.  But - again, my opinion - pandas puts these two functions in the core focus.    

If we do switch to pandas, everything would (have to be) backward compatible as far as end-users and developers are concerned.  However, there would be added flexibility that the ``values`` in the ``stress_period_data`` arguments could be ``DataFrames`` and that we could expose slicing and dicing functionality for the boundary condition packages for better inspection and investigation.  And there is ``DataFrame.to_records()`` for those that prefer recarrays.  The actual coding *should be* trivial...

**Comment by jbellino-usgs** [comment]
Hey Jeremy, glad to hear that you're working on additional pandas functionality—I'm actually having a bit of trouble with the way the `MFlist` object casts `DataFrames`, specifically for the case where WEL package pumping is 0 in the first stress period (predevelopment steady-state for a transient, regional model). I started digging into this on my own branch, but then remembered you were already working on it. The problem is that pandas chokes when you pass a "0" into the `DataFrame` constructor, i.e. line 393 of util_list.py:
```
# For 0 pumping in stress period 0, v == 0 and the DataFrame constructor chokes
for k, v in self.data.items():
    df = pd.DataFrame(v)
```
We could bypass any stress periods for which the value of the data item is 0, but this leads to problems down the line where `squeeze == True` and we start looking for columns where differences occur. Do you already have a solution for this?

**Comment by jtwhite79** [comment]
I think ``MfList`` is storing a '0' in ``data`` if ``itmp`` is zero (no entries).  Have you tried the ``__getitem__`` method (e.g. ``self[kper]``)?  I think its setup to return empty (maybe?).

I haven't started on anything regarding pandas yet, still waiting to hear if others think its ok to have pandas a dependency...

**Comment by jbellino-usgs** [comment]
Yes, I just tested and `self[kper]` returns `None` . I'm going to take a look at this code a bit more—I'm in the process of tracking down pumpage weirdness and want to be able to use `DataFrames`. I'll keep you guys updated on what I'm doing...it may end up as a pull request at some point.
