### ISSUE TITLE
External file formats

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#33]
Consider implementing a method for accommodating user defined formats for external files.

**Comment by jtwhite79** [comment]
Would this be for writing new external files when a model instance is written? or for dealing with previously-existing files that we just need to "pass through" (not loaded into memory)?  

I think it would be easy enough to attach a preferred or default ```int``` and ```float``` array format to the model instance that ```array_util``` could check for, but its more difficult to assign a preferred format to each array instance because they are buried in the package instances.

**Comment by jdhughes-usgs** [comment]
Dealing with previously existing files. Jason Bellino had some files existing files that got kicked. Any way to try and parse the file and come up with a format statement since the model dimensions are known?

**Comment by jbellino-usgs** [comment]
Looking at the external files I created with numpy.savetxt(name, X, fmt='%15.6E') shows that the first column has the correct number of digits, however subsequent columns have an extra whitespace character which is then throwing the reader into disarray (pun intended). Though the default delimiter is listed as '' in the numpy docs, using the default results in this behavior. It seems that the delimiter must be explicitly cast as '' when calling savetxt() in order to avoid the problem.

**Comment by jtwhite79** [comment]
That is a good catch - we are suffering from the same bug on the
write_txt() method...just added a fix to develop branch.  Thanks Jason!

**Comment by jbellino-usgs** [comment]
I'm glad that comment was useful. I realized out was more of a numpy issue so I ended up deleting it.
