### ISSUE TITLE
adding more stress periods not adjusting perlen size

### ISSUE THREAD

**Issue by rosskush** [modflowpy/flopy#371]
Hello, I am trying to load a model with flopy and am trying to adjust the nper and subsequently the perlen.

mf = flopy.modflow.Modflow.load(f=namfil,model_ws=mname,version='mfnwt',verbose=True)
`#` original nper = 12, original perlen = [30,30,30,....] (12 elements) 
dis = mf.dis

if i try:
`dis.nper` = 36
`print(dis.nper)` # updates to 36
 
but if i try:
`dis.perlen` = np.ones(36) * 30.34

I get 
Traceback (most recent call last):
  File "S:\AUS\HDR_Corpus\modeling\modflow_simple\ModflowModel\01_build_mf_v00.py", line 33, in <module>
    dis.perlen = perlen
  File "H:\Miniconda3\lib\site-packages\flopy\pakbase.py", line 121, in __setattr__
    array_free_format=old_value.format.array_free_format)
  File "H:\Miniconda3\lib\site-packages\flopy\utils\util_array.py", line 1679, in __init__
    self.parse_value(value)
  File "H:\Miniconda3\lib\site-packages\flopy\utils\util_array.py", line 2521, in parse_value
    str(value.shape))
Exception: Util2d:self.shape: (12,) does not match value.shape: (36,)

If I simply try:
`dis.perlen` = 30.34
print(dis.perlen) # i get a list of size 12 still and not the updated 36 

Thank you in advance.

**Comment by jtwhite79** [comment]
Hey Kush - I've tried to do this myself and I've found its easier to just make a new model instance, populate the non-temporal things (trivial), then build up the temporal items.  Not ideal, but the way things are setup is those transient containers are instantiated with the appropriate dimensions so that they can error trap later (and there is some confidence that the model instance in memory will actually work!).  In general, you can easy shrink (extract a subset) the number of stress periods (I've written a function for that if you are interested), but extending the number of stress periods is harder...

**Comment by rosskush** [comment]
Sounds good! appreciate the fast response, I'll just stick to rewriting the dis package for now.

**Comment by saedoquililongo** [comment]
Hello,

I know that this is a closed issue but I had the same problem and now I think I solved it (when rewriting the dis package I had other issues so I kept on trying to solve this). I went more deep into the codes and noted that, if you have a new nper length, you can not simply assign an array/list to perlen. To solve this I assigned an Util2d to perlen and worked!. These are the lines I wrote:

```
model.dis.nper = nper
model.dis.perlen = flopy.utils.util_array.Util2d(model,(nper,),np.float32,perlen,'perlen')
```

model is my modflow model, nper is a int and perlen is a list of size equal to the new nper. This applies to tsmult and steady, because they also have the problem rosskush stated.

Hope it helps in the future!
