### ISSUE TITLE
Error reading bcf-package and bcf-file

### ISSUE THREAD

**Issue by rabbl** [modflowpy/flopy#434]
We have a problem reading the bcf-data from an existing project.
Here you can find the detailed and reproduced error:

https://github.com/inowas/landelino-case-study/blob/add-well-package/load-bcf-file-error.ipynb

I have seen that #98 treats a problem which brings a similar error message. 
Could this be a format-problem?

**Comment by langevin-usgs** [comment]
You've indicated that the load is giving wrong results, but that isn't helpful for figuring out the problem.

And in the second part where you try to load the file directly, your bcf package has unit numbers in the array headers, and because you are loading only the bcf file and not the name file, it doesn't know how to interpret those unit numbers.

```
        11  1.00e+00(10G11.4)                   -1 Anisotropy factor(s)
         1.         1.         1.         1.         1.         1.         1.
```

I think you can probably pass in a

**Comment by rabbl** [comment]
In [4]: shows the content of the bcf-file, this are the expected values.
In [5]: shows part of the hk-data from the bcf-package from the loaded model

As you can see, the values of the layers > 0 are 0, but as you can see in the bcf-file, the values are bigger then 0.

**Comment by langevin-usgs** [comment]
You have laycon specified as 1, 2, 0, ...  HY is only specified for laycon 1 and maybe 2 (I forget).  So this means there is no HY data for the other layers, so flopy fills the bcf.hy array with zeros.  There should be a transmissivity array in there that has the values for the other layers.
