### ISSUE TITLE
Rotation in ModelMap

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#44]
Should we consider the x- and y-offsets to be relative to the lower left corner (rather than the upper left) and embrace a cartesian coordinate system??

**Comment by mbakker7** [comment]
+1 for me

make the coordinate system Cartesian.

**Comment by langevin-usgs** [comment]
The system is cartesian as it is now.  The issue is that the x and y offsets (and rotation) are specified relative to the upper left hand corner.  If the xoffset and yoffset are not defined, then they are calculated so that the origin is in the lower left hand corner, as you would expect.  Isn't this the PEST utilities gridspec approach?

**Comment by jdhughes-usgs** [comment]
It is the way the PEST utilities do it but I am not sure it is the best way. Lower left corner seems more intuitive. This is the corner that ESRI ASCII grid files uses.

**Comment by langevin-usgs** [comment]
The way it is now, the origin coincides with the model's row, and column origin.  I think people working with georegistered MODFLOW grids will more commonly have and report the upper left hand corner, although they could clearly come up with the left hand corner.  Lower left corner is also appealing for the reasons you state.  I don't feel strongly either way, but changing it now would break backward compatibility.

**Comment by langevin-usgs** [comment]
I suggest that we stick with the upper left corner for now.  We've burned this in.  We can add more options for specifying other corners, but someone could also make that transformation before creating the discretization.
