### ISSUE TITLE
Modflow 6 MFSimulation.load classmethod missing argument sim_namefile

### ISSUE THREAD

**Issue by tomvansteijn** [modflowpy/flopy#465]
The argument `sim_namefile` is listed in the docstring of the MFSimulation.load classmethod. However this argument is not available. The location of the simulation package is determined from the name and the workspace apparently. There is an attribute called `name_file`, however this is an instance of `flopy.mf6.modflow.mfnam.ModflowNam`.

**Comment by spaulins-usgs** [comment]
The argument sim_name_file will be removed from the docstring of MFSimulation.load on my next pull request. Please disregard it for now. You are correct that the location of the simulation namefile is determined by sim_ws. You can then set relative or absolute paths for each of your models and/or packages if you don't want everything in the same location.

The name_file attribute is an instance of the simulation name file (mfnam.ModflowNam is the simulation name file while mfgwfnam.ModflowGwfnam is the groundwater flow model name file). I don't recommend working with the name_file attribute directly unless you want to set the name file's options (everything else in the name file is automatically updated for you).  In the future flopy will have an interface to set the simulation namefile's options directly in the MFSimulation class so that the name_file attribute is no longer needed.

**Comment by tomvansteijn** [comment]
Thanks for the explanation. A related issue is that the simulation namefile's filename is always mfsim.nam. This is hardcoded. I would expect the filename to be based on the argument sim_name of the MFSimulation class. Wouldn't that be straightforward to implement?

Though I realize this is just a minor issue which causes no problems for my usage.

**Comment by spaulins-usgs** [comment]
I don't think MODFLOW-6 will work with a renamed simulation name file. According to the MODFLOW-6 documentation, 'The simulation name file is read from a file in the current working directory with the name “mfsim.nam”.' Additionally, MODFLOW-6's command line interface does not include an option to specify a simulation name file.

**Comment by tomvansteijn** [comment]
Thanks for the clarification!
