### ISSUE TITLE
DISU node numbering flexibility

### ISSUE THREAD

**Issue by geowat** [modflowpy/flopy#521]
This may be a long shot to look for such a feature in flopy, but I'm only looking for some tips how to tackle this - hopefully there is some implementation in flopy. 

We have a multi layer model built in DISV which we are trying to convert to DISU - DISV was created with the help of flopy+gridgen. Since DISU doesn't have a layer concept, would it be possible to start the node numbers from e.g. 100000 for 1st layer and 200000 for 2nd layer and so on. 

Second question is that since DISU does not have inactive nodes, when the cells are removed for being inactive - can the node numbering kept as original e.g. if the highest node number is 99000 in L1 (considering no inactive cells), highest number would be 99000 in all other layers too (assuming last node is active) even other layers have inactive cells (removed). 

Even node numbers are nothing but reference ids, the above two features would be helpful when converting DISV to DISU as nodes in boundary packages could be easily converted.

**Comment by langevin-usgs** [comment]
I'm not sure I understand your first question, but the node numbers need to start at 1 for the first layer.  

And we realize the issue about not having IDOMAIN for DISU, but that is a MODFLOW 6 problem.  We hope to add IDOMAIN capability to DISU at some point, but there are some complications that we need to think about.  

Keep in mind that the the flopy gridgen wrapper does have some methods for creating a MODFLOW 6 DISU package, so you could recreate your grid with gridgen instead of trying to convert the DISV model.

**Comment by geowat** [comment]
You have answered my first question if node numbering has to start from 1 in which case there is no point to explore the flexibility option in the second question which is probably not likely anyway. We will stick to gridgen wrapper as you suggested. Thanks!
