### ISSUE TITLE
Problem with LPF package using Modflow-USG

### ISSUE THREAD

**Issue by Danock22** [modflowpy/flopy#529]
I'm triying to use DISU, LPF and BAS packages to create a single modflow model. Modflow documentation says that both LPF and BAS are compatible with MODFLOW-USG, but the function of python _flopy.modflow.mflpf_ in flopy require a (layers, rows, cols) structure.
How can I create an unstructured mesh using DISU package (no nested layers and more than one) and set the hydraulic conductivities for each cell in the mesh?
On the other hand, I have not found any example of MODFLOW-USG (.nam, .bas, .lpf, etc., files) with several layers and more complex elements like voronoi graphs or triangle meshes. Do you have any one or do you know where I can find one?
Thanks for your help.

**Comment by langevin-usgs** [comment]
Sorry that the USG approach isn't documented better.  I agree that we need to provide a notebook that does a better job.  The trick for specifying three dimensional arrays can be seen in this example, which sets the ibound for a MODFLOW-USG model.  In this case, ibound is a list of two dimension arrays of size (1, nodelay[k]), where nodelay[k] is the number of nodes in layer k.

```
ibound = []
for k in range(disu.nlay):
    ibd = np.ones((1, nodelay[k]), dtype=np.int)
    ibound.append(ibd)
```

But you are also asking a general question about how to create meshes and make models in flopy for MODFLOW-USG.  While we do have some capabilities, most of them are for MODFLOW 6 (where there are examples for using triangular and nested grids to make flopy models), and not MODFLOW-USG.  But I've attached here a notebook example that someone put together for using GRIDGEN and flopy and MODFLOW-USG.  Maybe it will give you some ideas.

I'm going to close this issue, because it is not really a bug with flopy, but rather a valid complaint about our poor documentation for using flopy with MODFLOW-USG.  


[L_USG_GRIDGEN.ipynb.zip](https://github.com/modflowpy/flopy/files/3075339/L_USG_GRIDGEN.ipynb.zip)

**Comment by Danock22** [comment]
Thank you very much for your help. I think I'm going to work with _flopy.mf6.modflow.mfgwfdisv_ and _flopy.mf6.modflow.mfgwfdisu_.
