### ISSUE TITLE
What's happenend to SpatialReference?

### ISSUE THREAD

**Issue by briochh** [modflowpy/flopy#532]
Hi All,

I appreciate that there have been a lot of changes in the way spatial references are handled in flopy, and these methods have been getting a bit of (probably much needed) attention but...

I always used to set geographical spatial reference info using the `.sr` route, e.g.:
```
    m.sr.xul = 1234567.  # utm coord x 
    m.sr.yul = 7654321.  #utm coord y
    m.sr.proj4_str = 'EPSG:1111'
```
Should this still be functioning?
It seems to set the `m.sr` attribute, as before:
```
IN[33]: m.sr
Out[33]: xul:1234567; yul:7654321; rotation:0; proj4_str:+init=EPSG:1111; units:meters; lenuni:2; length_multiplier:1.0
```
BUT it no longer seems to propagate into the reference info in the `.nam` file:
`#xll:0; yll:0; rotation:0; proj4_str:EPSG:4326; units:meters; lenuni:2; length_multiplier:1 ;start_datetime:01-01-1950`

I am sure I am missing something but not sure if this is a designed deprication? If it is, how do I add this information to flopy modflow model instance using the new methods?

Thanks,

B

**Comment by langevin-usgs** [comment]
The idea is that everything now goes through a model grid object, which is attached to the model itself.  So in it's simplest form, you can just do this:

```
m = flopy.modflow.Modflow()
dis = flopy.modflow.ModflowDis(m)
m.modelgrid.set_coord_info(xoff=100., yoff=1000., 
                           angrot=34., epsg='EPSG:1111')
m.write_input()
```

And you will get a name file that has the information in it:

```
# Name file for MODFLOW-2005, generated by Flopy version 3.2.12.
#xll:100; yll:1000; rotation:34; proj4_str:EPSG:4326; units:meters; lenuni:2; length_multiplier:1 ;start_datetime:1-1-1970
LIST               2  modflowtest.list
DIS               11  modflowtest.dis 
```

All subsequent plotting and exporting of this model will use this information.  With sr it was a little confusing since there were so many places to specify grid location information (dis, sr, ModelMap, etc.).

**Comment by jdhughes-usgs** [comment]
There is an issue with the EPSG code in the name file in the example above. The default EPSG code (`4326`) is specified instead of the provided EPSG code (`1111`).

@spaulins-usgs and @jlarsen-usgs  we should probably just have one way to define the projection information. A suggestion is if `proj4_str=` string contains `EPSG:` with a trailing integer the EPSG code should be set to the integer and an equivalent proj4 string could be created by the `proj4` package. Otherwise if a `proj4_str=` string is defined without `EPSG` then it would define the `proj4_str` and `EPSG` would be `None`.

@spaulins-usgs and @jlarsen-usgs, another questions is if `length_multiplier` is always 1?

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs

I can start looking into this issue. My guess is that the ESPG code is not not getting called from the right place when writing the new name file.

As far as changing the input signature of the grid classes goes, how about replacing both `proj4_str` and `epsg` with `projection`. I foresee it being confusing to define an EPSG code as the `proj4_str` variable, since PROJ is a specific representation of a cartographic transformation information whereas `projection` is a fairly generic parameter name.

`length_multiplier` was somehow overlooked in the development of the grid classes. I can work on adding that parameter/functionality into the grid classes.

**Comment by briochh** [comment]
Thanks all, getting in through the `m.modelgrid.set_coord_info()` seems to be working for me, still having some issues with the epsg code in a `.nam` file being stomped on by the default when reading and writing but maybe that'll be fixed by @jlarsen-usgs PR (#534), or it may be somthing funny at my end.

**Comment by jlarsen-usgs** [comment]
ESPG code being written to the name file should be fixed. I'm going to close this issue.

**Comment by briochh** [comment]
Ace! Thanks @jlarsen-usgs!
