### ISSUE TITLE
LAYCON all zero when setting external

### ISSUE THREAD

**Issue by laat0003** [modflowpy/flopy#561]
Hi,
When setting external to true with change_model_ws(reset_external = True), BAS.ifrefm becomes False. If you then load BCF's LAYCON you get all zeros because lcode (line 316 in mfbcf.py) is being made double digits with the extra "0" added. This makes len(t[k]) greater than 1 (line 322 in mfbcf.py) and laycon is then being read as the "0" that was added.

Would not have been an issue if I hadn't just spent 1.5 weeks trying to calibrate the thing with Pyemu. 

Tariq

**Comment by langevin-usgs** [comment]
Thanks, @laat0003.  In looking at the code, it seems like there might be a problem with flopy BCF support.

 If FREE is not specified, and there are more than 40 layers, then the load does not look like it will work, because the (40I2) format would require additional readline calls, which don't appear to be there.

 According to the online guide (https://water.usgs.gov/ogw/modflow/MODFLOW-2005-Guide/index.html?bcf.htm), this is actually Ltype and not LAYCON, which means there can be two digits.  In flopy we are filling an intercellt and a laycon variable, but I'm not sure how well this has been tested.

I'm not sure what is happening with the change_model_ws(reset_external = True) in your particular case.  It seems to me like you would first load the model with the FREE format, then change the workspace and reset to external, and then write the model.  How is it that you read the model after you've changed the works space?

Either way, it looks like there may be some issues with BCF loading that will need to be addressed.

**Comment by laat0003** [comment]
Cheers for the rapid response. 

I'm jumping between my heterogeneous cluster at home, which I use for calibration and work where I do most of the post-processing. Accordingly, I always end up loading a model again after it has been reset and run as external with either PEST or PyEMU.  

I am loading a 5 layer MF2000 model file with "1 3 3 0 0" (single digits for Ltype) as the entries for what I believe to be the LAYCON variable making L1: unconfined, L2 and L3: convertible and L4 and L5: confined. I didn't develop the model originally (a VM relic from 2011 still used by Fed Gov) but am just looking at what is in the original input file. If I load the model after it has been run as external I get LAYCON as all zeros. I double checked my list files and it seems that if I load the original model and write external files LAYCON is transferred correctly. The LAYCON all zeros seems to occur when loading the model again.

**Comment by laat0003** [comment]
If I manually enter a zero before each LAYCON entry in the BCF file that was created when resetting to external, then it appears to work as expected.

**Comment by jwhite-usgs** [comment]
Can you post the model files for debugging (if they aren't too large)?

**Comment by laat0003** [comment]
[LB2011test.zip](https://github.com/modflowpy/flopy/files/3195862/LB2011test.zip)

I've attached a nam, dis, bas and bcf files in zip archive. These are the originals. If you use them to load then reset external and write the files it will write the LAYCON variables correctly and MODFLOW will run fine using the correct Ltype settings. If you then load the external model, it reads the LAYCON variables incorrectly. I worked around it by placing a zero infront of each LAYCON entry. That is instead of "1 3 3 0 0" I used "0103030000" and then it read fine.

**Comment by jtwhite79** [comment]
ok - I think the issue in `mfbcf.write()` - looking at the version of mf2005 code I have (starting on line 123 of gwf2bcf7.f), it looks like it is always expecting two digits for each entry, the free format part only applies to the space between the two digits.  Ive just patched this in `mfbcf.write()` and waiting for travis to tell me what else is broken...

**Comment by laat0003** [comment]
Damn you guys are quick. Props. :)
