### ISSUE TITLE
HeadFile returns one-based kstp, kper for freyberg_multilayer_transient example

### ISSUE THREAD

**Issue by aleaf** [modflowpy/flopy#566]
```python
from flopy.utils import binaryfile as bf
hdsobj = bf.HeadFile('../examples/data/freyberg_multilayer_transient/freyberg.hds')
hdsobj.kstpkper
```
returns `[(1, 1), (1, 2), (1, 3)...`

`autotest/t017_test.test_binaryfile_read` has an assert that `kstpkper[0] == (0, 0)`, but it passes, so not sure what the difference is between the two cases.

```hdsobj.get_data(kstpkper=(1, 1))``` for the freyberg_multilayer_transient case returns an error, but ```hdsobj.get_data(kstpkper=(0, 0))``` works as expected.

**Comment by langevin-usgs** [comment]
It looks like the information stored in hdsobj.kstpkper is one-based, but the get_data method takes zero-based values and adds a one in order to extract.  I agree that is not clean if someone is looking at hdsobj.kstpker as you are.  Simple fix is to call the get_kstpkper method.  This returns zero-based values.  This is a bit of a remnant from before we went all zero-based.

**Comment by langevin-usgs** [comment]
@aleaf, I'm going to close this for now, but it does seem like there could be some refactoring of the datafile utilities to be all zero-based, or at least to better hide the one-based arrays.  Bottom line is that users should call the `get_kstpkper()` methods instead of accessing the `.kstpkper` attribute directly.
