### ISSUE TITLE
joining model_ws path to external array path name

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#6]
I disabled this in util_2d because it produces external file paths that were absolute which means the model structure is not portable.  Is this ok with everyone?

**Comment by jjstarn** [comment]
okay with me.  I always use relative paths.  Does this still work?

On Wed, Jan 21, 2015 at 12:20 PM, jtwhite79 <notifications@github.com>
wrote:

> I disabled this in util_2d because it produces external file paths that
> were absolute which means the model structure is not portable. Is this ok
> with everyone?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modflowpy/flopy/issues/6>.
>



-- 
Jeff Starn Ph.D.
Research Hydrologist
USGS National Water-Quality Assessment
101 Pitkin Street,  East Hartford, CT 06108

jjstarn@usgs.gov
office: (860) 291-6746
cell: (860) 335-8381

**Comment by mbakker7** [comment]
I use model_ws path all the time.
Does this not work anymore?

**Comment by langevin-usgs** [comment]
We made a change to model_ws in order to import models.  Apparently the
change broke some things in that external arrays are referenced with
absolute paths.  This is bad.  Will figure out a workaround over the next
week or two as we prepare for the class.













*Christian LangevinResearch HydrologistOffice of GroundwaterU.S. Geological
Survey411 National CenterReston, VA 20192Office: 703-648-4169Fax:
703-648-6693Email: langevin@usgs.gov
<langevin@usgs.gov>https://profile.usgs.gov/langevin
<https://profile.usgs.gov/langevin>*

**Comment by mbakker7** [comment]
Ok. Thanks for the explanation.

**Comment by kwilcox** [comment]
@jtwhite79 @langevin-usgs FYI - this did break the loading of OPEN/CLOSE lines that already use relative paths. The issue is that `util_array.parse_value` is not respecting a working directory or `external_path` when asserting that a file exists.

I've made a small change to a local copy of util_array.py that will suit me for the time being. What should I expect going forward? An additional kwarg on the Modflow.load method for `external_path` that will propagate down to `util_2d`?

**Comment by jtwhite79** [comment]
I imagined it would break some things. I think Chris and Joe are actively developing - they will probably come up with a fix. If not I'll take a stab at it

**Comment by jtwhite79** [comment]
I just pushed an attempted fix for this issue.  The Modflow.load() method now also takes an optional "namefile_path" arg (default is '.'), which is appended to the model instance as a attribute and is propagated down to the util_array load methods.  So now "model_ws" is where you want to the new model files to be written and "namefile_path" is the relative path to the existing model files.  I had to hack it in to util_2d so that any "open/close" arrays in the existing model files become "internal" arrays in the new model files.  Hopefully this isn't a problem.
