### ISSUE TITLE
mp7.py doesn't get laytyp correctly for non MODFLOW 6 model.

### ISSUE THREAD

**Issue by htran84** [modflowpy/flopy#600]
Line 329:
laytyp = self.flowmodel.laytyp
This code will always return nonetype because the laytyp property is specified inside a flow package.
For example, if I'm using upw, I have to write laytyp = self.flowmodel.upw.laytyp to get to correct value.

**Comment by jlarsen-usgs** [comment]
Ideally, line 329 should work fine, since the base class for all model objects (not limited to modflow 6) is defined as

```
    @property
    def laytyp(self):
        if self.get_package("LPF") is not None:
            return self.get_package("LPF").laytyp.array
        if self.get_package("BCF6") is not None:
            return self.get_package("BCF6").laycon.array
        if self.get_package("UPW") is not None:
            return self.get_package("UPW").laycon.array

        return None
```

however, I see the issue. The UPW call inside the base class is looking for `laycon.array`, which doesn't exist instead of `laytyp.array`.

I'll submit these changes soon.
Thanks for pointing this out
