### ISSUE TITLE
MODFLOW 6 problem reading/writing ja array.

### ISSUE THREAD

**Issue by Danock22** [modflowpy/flopy#603]
I'm using unstructured grid in modflow 6 (DISU package). When I create the _ja_ array, I use the format: -1 2 5 7 (node 1 is connected to the nodes 2, 5 and 7).  If I read the simulation that I have wrote, flopy loads _ja_ array subtracting 1 to all nodes, i.e. the format change to -2 1 4 6 for this examples, consequently, if I wrote this simulation again, the _ja_ array would be bad written.

**Comment by langevin-usgs** [comment]
@spaulins-usgs, can you take a quick look at this?  The DISU package allows the user to enter a negative node number as described below.  Flopy needs to take the absolute value of these numbers before converting them to zero-based values.

![image](https://user-images.githubusercontent.com/3372403/60266756-563bc580-98ae-11e9-85d3-29258ed160f7.png)

Also, it would be nice if upon writing out the JA array, that flopy would write out the connections for each cell on a new line.  This would make it much easier to look at.  In fact, all the connection arrays (hwva, cl12, etc.) should be written this way if possible.  Perhaps we need to mark these types of arrays in the definition files somehow so that you recognize they they are "jagged".

**Comment by spaulins-usgs** [comment]
@Danock22 While I do see a potential problem with the way flopy is handling the ja array, so far I have not been able to reproduce the problem you describe. Some additional information may help me track this down. What version of flopy are you using? Are you storing the ja array in the disu file or in an external file? If external, is the external file a text of binary file?

@langevin-usgs Yes I will make the arrays jagged when writing them out to a file. Though internally they will still be stored as ndarrays.

**Comment by Danock22** [comment]
- The version of flopy that I'm using is 3.2.11.
- I'm storing the _ja_ array in the DISU file.

I'm going to explain the problem in detail:
I want to write the simulation files. For this, I create all the arrays that DISU package needs, but I'm going to talk just about two: _ja_ and _cell2d_ . When I create the _cell2d_ array, the first item that I need is _icell2d_ (the numer id of each cell). In flopy, I have to enumerate them from 0 to nodes-1, but when a write the simulación using `sim.write()`, flopy changes the enumeration from 1 to nodes. Now, if I load this files using `flopy.mf6.MFSimulation.load()`, the enumeration changes again from 0 to nodes-1. Here, there's not problem. But, this is not the case of _ja_ array.  `sim.write()` writes _ja_ array using the same numeration that I used in python, for example, if the numeration is 0 to nodes-1,  `sim.write()` writes _ja_ using "0 to nodes-1" enumeration or if the numeration is 1 to nodes, _ja_ array is 1 to nodes. The problem is that when I load the simulation using  `flopy.mf6.MFSimulation.load()`, this function substracts 1 to enumeration (like _cell2d_ array). Then, if I used "0 to nodes-1" enumaration, it chages to "-1 to nodes-2", or if I used "1 to nodes" enumeration, it changes to "0 to nodes-1" enumeration. 
This means that if I write and load the simulation several times, the numeration will change subtracting 1 every time.

I attached 5 DISU files where I loaded and wrote one example four times. Look how the _ja_ array changes.


[DISU_files.zip](https://github.com/modflowpy/flopy/files/3339986/DISU_files.zip)

**Comment by spaulins-usgs** [comment]
@Danock22 I checked in a fix here:

https://github.com/spaulins-usgs/flopy

The fix was made to the develop version of flopy so you will need to replace all of flopy. Let me know if it works for you. I have not yet implemented writing the arrays as jagged arrays, though I plan to do that next week and then pull all of my changes into the main fork.

**Comment by Danock22** [comment]
I updated flopy to version 3.2.12. It is working very well for the moment.
