### ISSUE TITLE
MODFLOW 6 Internal factor does not allow to load the simulation

### ISSUE THREAD

**Issue by Danock22** [modflowpy/flopy#606]
I load a simulation that I wrotw before. After that, I change the value of _ja_ array like this: `disu.ja.set_data( disu.ja.array + 0 )` (no value changes). Then, I write the simulation again using `sim.write_simulation()`. I checked the DISU file and the internal factor value changes from 1 to 1.0.
This changes does not allow to load again the simulation. This error appear:
_Data "ja" with value "1.0" can not be converted to int._

**Comment by spaulins-usgs** [comment]
Verified that this is a bug. I have added a fix to the version of flopy here:

https://github.com/spaulins-usgs/flopy

Please try this out and let me know if it fixes your problem. Note that I also just added formatting for the disu jagged arrays, so the ja array should now also output with a cleaner format that is easier to read.

**Comment by Danock22** [comment]
the problem still persists :(

**Comment by spaulins-usgs** [comment]
Since I am not seeing the bug anymore and you are, let's compare the steps we are using to reproduce it. Here is what I did. Let me know if you are doing something different reproduced the bug.

I am using the first disu file from the  DISU_file.zip file you posted. I added some basic simulation files to it in order to make a working simulation. I then loaded the simulation, set the ja array, and wrote it back out with the following code:

    # load simulation
    sim = MFSimulation.load(model_name, 'mf6', exe_name, pth)
    model = sim.get_model()
    disu = model.get_package('disu')
    # test from issue #606
    disu.ja.set_data(disu.ja.array + 0)
    # write simulation to new location
    sim.write_simulation()

I ran this code twice to confirm that the written files could be read again. The written disu file is included in this message (flow.zip). As you can see in flow.zip flopy left the factor as "1", but did reformat the ja array to make it easier to read.

Please let me know if you are doing something different to reproduce this problem. Also, please make sure you are using the latest mfdata.py flopy file from here: https://github.com/spaulins-usgs/flopy. The fix in this file is what fixes the bug you described above. Specifically like 451 to 454 should read:

                if data_type == DatumType.integer:
                    int_format.append(str(int(layer_storage.factor)))
                else:
                    int_format.append(str(layer_storage.factor))

[flow.zip](https://github.com/modflowpy/flopy/files/3352271/flow.zip)

**Comment by Danock22** [comment]
I'm using the mfdata.py file that you say, but a new prblem appears writing the DISU package:

`MFDataException: An error occurred in data element "ja" model "mf6_webinar2" package "disu". The error occurred while converting data in the "get_data_string" method.
Additional Information:
(1) Could not convert data "1" of type "DatumType.integer" to a string.
(2) Error occurred while writing data "ja" in block "connectiondata" to file "/home/daniel/Desarrollo/mf6_webinar2/./mf6_webinar2.disu".`

**Comment by spaulins-usgs** [comment]
I can only reproduce that error if I don't use the latest mydatautil.py that I posted on my fork here: https://github.com/spaulins-usgs/flopy

I have several fixes in that fork that may effect you, including one that will format the ja array for you. Please make sure you are using all the latest files from my fork. The easiest way to do this is to download that fork and copy the entire flopy folder (trunk/flopy) to the python lib/site-packages/flopy folder (replace all).

**Comment by Danock22** [comment]
I replaced all "lib/site-packages/flopy" folder downloading  all the latest files from your fork [https://github.com/spaulins-usgs/flopy](https://github.com/spaulins-usgs/flopy) and the error "_(1) Could not convert data "1" of type "DatumType.integer" to a string._" still persists.
I found exactly where the algorithm crashes.  In line 127 of _mfdatautil.py_, the algorithm try to computes the length of a `numpy.int64` variable and this is a `TypeError`. So, I changed the type of each _ja_ element to `numpy.int32`  (line 125 of _mfdatautil.py_ file) and it works, but when I load the simulation, the _ja_ type changes to `numpy.int64` again.

**Comment by spaulins-usgs** [comment]
While I could not reproduce this problem, I think it might have something to do with our systems having different default numpy integer types. I changed the code to explicitly defined numpy integers as numpy.int32 (in some places numpy.int was being used). Please give this code a try:

https://github.com/spaulins-usgs/flopy

If that does not work try changing line 127 of mfdatautil.py to:

if isinstance(val, np.int32) or isinstance(val, np.int64):
