### ISSUE TITLE
spatial reference transformation issue with the new cross-section plot class 

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#660]
The new cross-section class doesn't do spatial transformation even when the spatial reference information has been configured through DIS and modelgrid class. 
For example, let's say I have loaded a model mf, then I configure the spatial reference, 

`mf.modelgrid.set_coord_info(xoff=xoff, yoff=yoff, angrot=0)`

Then, I do the plot, 
`flopy.plot.PlotCrossSection(model=mf, line=line={'Row': 10})`

The cross-section plot still starts from 0 rather than xoff.

**Comment by jlarsen-usgs** [comment]
@flydream0428, I'll take a look at this issue.

**Comment by jlarsen-usgs** [comment]
The issue in the plotting code. Currently the plotting code is translating the modelgrid to model coordinates (i.e. xoffset=0, yoffset=0, and angrot=0). I'm working on a patch for this and will submit a PR to translate the cross sections back to geographic coordinates.

**Comment by jlarsen-usgs** [comment]
@flydream0428, I've added a new feature to the `PlotCrossSection` class that allows the user to plot in geographic coordinates. The default behavior was, and still is, to plot cross sections with the cross sectional distance on the x-axis. This behavior is useful for arbitrary cross sections, because the code does not have to choose a projection direction to display the data from. 

To plot using geographic coordinates you can use

`pxc = PlotCrossSection(model=mf, line={"column": 10}, geographic_coords=True)`

Examples can be found in the [flopy3_PlotCrossSection_demo.ipynb](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_PlotCrossSection_demo.ipynb)
