### ISSUE TITLE
SSM package mtssm.py: raise error when there is no concentration data for the first stress period.

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#674]
An error message will be raised when there is no data for the first stress period in the stress_peiod_data for the SSM package. For example, if we change all the ssm_dat[0] to ssm_dat[1] in the notebook example in the repository, (https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_multi-component_SSM.ipynb). A key error will be encountered. 

If I manually add data such as ssm_dat[0] = 0, then a "no itype" error will be raised. 

The set-up on INCRCH and INCRCH also doesn't make sense to me. For the example above, the first few lines of the ssm file is:

 T F T F F T F F F F F F F F F F
       202
         1
         0         0                           -1 #crch11
         0         0                           -1 #crch21
       102         0 # stress period 1

What is the second 0 and -1 in line 4 and 5?  I cannot find their definition in the MT3D-USGS manual/

**Comment by emorway-usgs** [comment]
@flydream0428 The issue with changing `ssm_dat[0]` to `ssm_dat[n]` should be resolved with #756. 

Regarding your other question, is the input that you showed (quoted below) from flopy?  Was MT3DMS (or MT3D-USGS) complaining about this input?  Without the rest of your input, it's hard to tell what could be going on, it could be that the first 0 would indicate that a constant value is going to be used for the entire array and the second 0 is indicating what the concentration of the recharge is.  Not sure about the -1

> T F T F F T F F F F F F F F F F
> 202
> 1
> 0 0 -1 #crch11
> 0 0 -1 #crch21
> 102 0 # stress period 1

The pending release of flopy (3.3.0) will have the fix for ssm_dat[n]
