### ISSUE TITLE
Gridgen to_disu6 errors

### ISSUE THREAD

**Issue by mwtoews** [modflowpy/flopy#678]
Test `t061_test_gridgen.py` should add a test for `.to_disu6(fname, writevertices)`. A quick attempt to use the module raises several errors:
```
>>> g.to_disu6('x.disu', True)
  File "flopy/utils/gridgen.py", line 1302, in to_disu6
    f.write('  NVERT {}\n'.format(gridprops['nvert']))
KeyError: 'nvert'
>>> g.to_disu6('x.disu', False)
Traceback (most recent call last):
  File "flopy/utils/gridgen.py", line 1321, in to_disu6
    a = gridprops[prop]

KeyError: 'ihc'
```
And further down in the source file, another error:
> ./flopy/utils/gridgen.py:1341:28: F821 undefined name 'nodes'

Tests for `.to_disv6(fname)` are also absent (and should also be added), but this method at least writes a file.

**Comment by langevin-usgs** [comment]
I'll take a look.  Those methods should work, and I apologize that they don't.  I haven't been using them as much because the methods, get_gridprops_disu6() and get_gridprops_disv().  I've found that it's easier to call these methods and get back a dictionary of everything needed to instantiate these packages directly, rather than using the to_dis6() or to_disv() methods.  I've made some recent changes in here to support the new modelgrid capability and remove spatial reference, and I must have broken some things, which wasn't caught because of the lack of tests.
