### ISSUE TITLE
mf.py::load() method

### ISSUE THREAD

**Issue by ndeeds** [modflowpy/flopy#70]
ext_unit_dict[].filetype is set to lowercase when the dict is populated, but then is compared to an uppercase filetype from load_only:

![image](https://cloud.githubusercontent.com/assets/16090529/11516402/88766f88-9848-11e5-837e-9c5fe2d30089.png)

populating the load_only list with uppercase filetypes also causes this comparison to fail further down, so none of the packages specified in load_only actually get loaded:

![image](https://cloud.githubusercontent.com/assets/16090529/11516559/9f2ea276-9849-11e5-8a8c-e446f40d548d.png)

I wasn't sure if you guys had a convention for whether the filetypes should be upper or lower case, so I wasn't sure what the right fix should be. I hacked something in there for myself to get it to work temporarily.

**Comment by jtwhite79** [comment]
Hey Neil - it looks the ```filetype``` attribute of ```ext_unit_dict``` is not being cast up or down (yikes), so I forced ```filetype``` to be uppercase in ```mfreadnam.parsenamfile()``` since that is what we are expecting in ```load```.   Added a new test to t008_test.py to test ```load_only```

Also, it looks like we were loading ```DIS``` twice: once near line 400 and then again in the main load loop, so I added an extra conditional to prevent.
