### ISSUE TITLE
aggregation method in util_list.py

### ISSUE THREAD

**Issue by tomvansteijn** [modflowpy/flopy#764]
Duplicated list entries are aggregated using `dfg.sum()` in flopy\utils\util_list.py, get_dataframe, line 473. Summing is appropriate for conductances but not for stages / head levels / river bottoms. For example, when having two drain boundary conditions in the same node, flopy will create a single entry in the stress period data of the DRN package, containing the sum of conductance (correct) and the sum of the drain elevation (not correct?).

I think the function get_dataframe should be aware of the column names to apply the right aggregation function. Or is aggregation necessary at all?

**Comment by mbakker7** [comment]
For the DRN package, I don’t think anything should be aggregated. Or it
should be a weighted sum of the drain levels. But that would make it a
weird military-level drain. That doesn’t work either I think.

**Comment by langevin-usgs** [comment]
I agree that there should be no aggregation, or it should be aggregated with a keyword, but not used as the default.  I imagine part of this was so that data frames could be used to operate with grids.  I know that this has been problematic for creating NetCDF files from MODFLOW input and output, because the underlying foundation is a grid.  @jwhite-usgs, do you have any thoughts on this?  I suspect you were the originator of this aggregation. (That sounds a lot like "suspect of this aggression"!)

Line is here: https://github.com/modflowpy/flopy/blob/8d3538328f2cd54e5ef43a74aeda6cad6b573de6/flopy/utils/util_list.py#L473

**Comment by jdhughes-usgs** [comment]
@langevin-usgs @jwhite-usgs is this resolved?

**Comment by tomvansteijn** [comment]
Not yet resolved in the develop branch I think. I can propose a fix and PR, but I am not aware of specific requirements for list data with respect to e.g. NetCDF. I do think the current implementation gives rise to modelling errors, albeit rather obvious ones, especially in areas with lots of drainage.

**Comment by jdhughes-usgs** [comment]
Reopen if #1033 did not resolve this issue.
