### ISSUE TITLE
problem with shapefile export and xul, yul

### ISSUE THREAD

**Issue by hwreeves-USGS** [modflowpy/flopy#789]
I am working in the 'develop' branch, flopy-3.2.13-py3.7

When trying to export a shapefile from the RIV package, the grid is sent to xul, yul = (0,0) 
and not the values set in the spatialreference.  I printed the spatial reference and it is OK.

If I make a little array of river cells, then I can use write_grid_shapefile.

These give a shapefile with the right attributes table, but the corner at (0,0)

```
mf.riv.export(os.path.join(gis_path, "modflow_riv2.shp"))
flopy.export.shapefile_utils.model_attributes_to_shapefile(os.path.join(gis_path, 'modflow_riv3.shp'), mf, package_names=['RIV'])

```

This works

```
rivarray = np.zeros(shape=(mf.dis.nrow, mf.dis.ncol), dtype=int)
for index, cell in sfr.reach_data.iterrows():
    rw = cell.i
    cl = cell.j
    if (ibound[rw, cl] > 0):
        rivarray[rw, cl]  = 1

arriv = {'RNODE': rivarray}
flopy.export.shapefile_utils.write_grid_shapefile(os.path.join(gis_path, "modflow_riv.shp"),
                                                           mf.sr,
                                                           arriv)

```

**Comment by jlarsen-usgs** [comment]
@hwreeves-USGS 

Hi, the issue that you're experiencing is due to the `SpatialReference` class being deprecated in flopy. Instead of setting spatial reference information in the `SpatialReference` class, you should set it in the `Grid` class for your model. You can access the modelgrid by:

```
mf.modelgrid
```
and can set coordinate information using the offsets and rotation from the lower left corner of the model using:

```
xll = 12345
yll = 11223
rotation = 30
mf.modelgrid.set_coord_info(xoff=xll, yoff=yll, angrot=rotation)
```
or if you are not able to get the lower left corner offsets, you can use this line of code to calculate them

```
xul = 100
yul = 200
rotation = 20
mf.modelgrid.set_coord_info(angrot=rotation)
xll = mf.modelgrid._xul_to_xll(xul)
yll = mf.modelgrid._yul_to_yll(yul)
mf.modelgrid.set_coord_info(xoff=xll, yoff=yll, angrot=rotation)
```
after setting your offsets in the modelgrid instead of the spatial reference flopy will export as expected.

**Comment by hwreeves-USGS** [comment]
Thanks -
