### ISSUE TITLE
Bug in get_empty() of class MfList in util_list.py

### ISSUE THREAD

**Issue by etiennebresciani** [modflowpy/flopy#811]
The line `d[:] = -1.0E+10` (called as part of test_mflist_add_record() in t021_test.py) is throwing me the error:
> OverflowError: Python int too large to convert to C long

I can correct this by writing instead: `d[:] = -1.0E+9`. With this correction, all the tests pass successfully. Let me know if you want that I submit a PR with this. I wanted to open an issue because I find it weird that it happens to me if it does not happen to others.
Configuration:
* python 3.7.6
* numpy 1.17.4
* Up-to-date with flopy develop (commit 0d152513d4ecb84fd474cb0495dd0676f05d5b72)
* Windows 10

**Comment by langevin-usgs** [comment]
I confirm that I get this same error when running t021_test.py on Windows.  Because d has layer, row, and column in it, which are integers, these can't be set to that value.  Not sure how it worked before. 
 I guess the goal here is to fill d with a marker to show a user that the value is bad and that it needs to be set.  But I think maybe we can just leave all the values at zero (an alternative might be to use -9999 or something like that).  I think maybe we just leave d at zero, in which case you could just remove the d assignment line (`d[:] = -1.0E+10`) as d is created with `np.zeros()`.  Feel free to submit a PR for this.  I wonder why nobody has complained about this yet.  Maybe this is relatively new to numpy on Windows?
