### ISSUE TITLE
UZF MF6 Error

### ISSUE THREAD

**Issue by MostafaGomaa93** [modflowpy/flopy#821]
I am building a transient mf6 model with the use of UZF package. I have 23302 cells using Disv package. when I try to run the model, I got this error:

forrtl: severe (41): insufficient virtual memory

I notice that this error only exists when activating the UZF package. I also notice if I decrease the number of the UZF cells to for ex only 100 cells, the model will run but will not converge.

I am confused by the meaning of insufficient memory!!. Does this error mean something wrong with the UZF data I used or Does it really mean my computer memory can't handle this model?

Thanks in advance

**Comment by spaulins-usgs** [comment]
This issue belongs in the MODFLOW 6 project.  You can add the issue here:

https://github.com/MODFLOW-USGS/modflow6/issues

Though first make sure you have the latest version of MODFLOW 6, there was a UZF memory leak problem fixed back in April of 2019:

https://github.com/MODFLOW-USGS/modflow6/issues/107
