### ISSUE TITLE
inconsistent behaviour of sim.write_simulation() and sim.plot() (MF6)

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#828]
I am creating a DISV package (MF6) using flopy and I noticed an inconsistent behaviour between the methods:

sim.write_simulation() 
sim.plot()

In order to make write_simulation() work, cell2d has to be defined as follow:

cell2d = [[icell2d, xc, yc, ncvert, idver1, idver2, ...], .... ]

in order to make sim.plot() work DISV, cell2d() has to be defined as follows:

cell2d = [[icell2d, xc, yc, ncvert, [idver1, idver2, ...]], .... ]

You can find a simple script here 

https://www.dropbox.com/s/nw7yai7zw1hd5i4/test_grid_mf6_2lay.7z?dl=0

that demonstrates the issue. In the script I defined cell2d in two different ways. Please comment and un-comment one of the two definitions to test the functions above.

I also noticed by writing the DISV package that the numbering of the vertices and cells should be 0 indexed in the python script. However, the help page here (https://modflowpy.github.io/flopydoc/mfgwfdisv.html?highlight=disv#module-flopy.mf6.modflow.mfgwfdisv) says the opposite.

**Comment by spaulins-usgs** [comment]
Cell2d should be defined without the extra [] around idver.  I am not sure how it is working at all with the [] around idver. When I try your example with the extra [] it does not work, even for plotting.  Concerning the plotting, I verified that if I add an npf package to your example and then do a sim.plot(), it plots the k from the npf package fine.  While "sim.plot()" does not plot anything but a solid block with only the disv package, I believe this is by design since grid lines are not plotted and there are no values on the grid to distinguish between cells. @jlarsen-usgs, am I correct that this is the expected behavior?

@giovannifi, you are correct that the vertices and cells are 0 based in python.  I think the problem with the documentation is that document definition files are shared between flopy and MF6, and it is just repeating the description from the MF6 documentation.  @langevin-usgs, is there anything we can do about this?

**Comment by jlarsen-usgs** [comment]
I agree that Cell2d should be defined without the extra [] around idver. I tested your script and sim.plot() would not work with the extra [] around idver. sim.plot() only plots arrays and does not plot the modelgrid by design. Because the layer elevations are defined as a constant value, this returns a solid color. 

If you want more control over plotting use the `flopy.plot.PlotMapView` class. This class provides functionality to layer modelgrid boundaries and arrays and has a whole bunch of other built in functionality. Examples can be found [here](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3.3_PlotMapView.ipynb)

**Comment by giovannifi** [comment]
All good this can be closed. I reinstalled flopy and everything works OK and consistently. It is possible that I corrupted some files. Sorry for the time waste with this.

**Comment by giovannifi** [comment]
Closing the issue
