### ISSUE TITLE
vtk export: adding new functionalities

### ISSUE THREAD

**Issue by etiennebresciani** [modflowpy/flopy#833]
I have been developing a few new functionalities for exporting data in vtk format. Namely:
* Exporting the data in vtk ImageData (.vti) or RectilinearGrid (.vtr) formats when possible, instead of always UnstructuredGrid (.vtu), since this will tremendously reduce file volume and will speed up subsequent operations (e.g. in Paraview)
* Exporting vectors (e.g., specific discharge)
* Improved interpolation for values at vertices

However, from the comments on issue #666, I am noticing that somebody might already be working on vtk functionalities. What is the status of this work? Should I rather wait before submitting anything, so as to avoid possibly-difficult conflicts?

Secondly, I am also a bit uncomfortable with submitting changes because the current regression tests for vtk (i.e., t050) are quite weak. Namely, the tests only check that the code runs without error: they do not check what is actually written. Would someone have worked on having more comprehensive tests (I realize that this may require a vtk reader)? Should I still submit a PR regardless (after a few manual checks, of course)?

**Comment by langevin-usgs** [comment]
In flopy version 3.2.13 we revised much of the VTK export functionality.  I don't think we have any other ongoing efforts so whatever you can contribute would be greatly appreciated.  You did a nice job with your last PR, which included comprehensive testing, so it would be great if you could do that again; feel free to improve the existing vtk tests.  

Couple of things to keep in mind:  (1) if you decide that we need a vtk reader in order to validate the files, then that would need to be added to the travis dependencies, unless you wrote your own, (2) we need to be comprehensive, but frugal, with the testing due to time limits on Travis CI (50 min for a single configuration I think), and (3) I think we support two types of vtk grid representations -- one with flat cell tops and bottoms (stair stepped), and another smoother representation where elevations are defined at vertices.  It would be nice to support both of them.

My understanding is that if the velocities are done correctly, then it would be possible to do streamlines and particle movement in Paraview.  At some point, we should probably post some instructions for using Paraview with flopy output.

@martindjm was involved in the last revisions to the VTK functionality.  Feel free to comment if you have any thoughts.

**Comment by etiennebresciani** [comment]
Thanks for the quick reply.

(1) I won't implement a vtk reader (at least for now). However, I came up with an idea to better validate the tests: we can open the files and assert that the total number of bytes is unchanged. The total number of bytes is a fairly good indicator of the file content. For formatted data, I think it is even somewhat sensitive to the actual values, because randomly-occurring trailing zeros are automatically removed when the file is written. This won't be the case for binary data, but still, this will already be a much improved validation.

(2) I won't make the tests runtime longer. I am already frustrated by their lengthy runtime (I like to run the tests often). In fact, I would strongly argue for decreasing the tests runtime as much as possible. (This should not be too hard. For instance, there is no point in testing the 1097 time steps of the Freyberg example to test transient stuff... only a few time steps should be enough.)

(3) I won't change the support for the two types of vtk grid representation. I will just add new functionalities.

(4) You read my mind: my objective is indeed to do streamlines in Paraview.

**Comment by martindjm** [comment]
I think exporting the data in (.vti) or .(vtr) formats when possible is a great idea.  I was going to implement this but have not got around to it.

**Comment by etiennebresciani** [comment]
Ok, I will submit a PR when I am finished.

Question: would you make it a default, or rather leave .vtu as the default export format?

**Comment by langevin-usgs** [comment]
I think the default should be the one that gives the most logical output format, which will not be .vtu for rectilinear grids.  I'm excited to see what you come up with.  Thanks for taking this on.

**Comment by etiennebresciani** [comment]
Sounds good. I should be done soon.

**Comment by langevin-usgs** [comment]
Closing this.  Thanks!
