### ISSUE TITLE
No thickness available for flopy.mt3d.Mt3dBtn with flopy.mf6

### ISSUE THREAD

**Issue by wkitlasten** [modflowpy/flopy#904]
I am using the develop version of flopy (3.3.1) with the latest release of mt3d-usgs and mf6. I am getting errors with flopy.mt3d.Mt3dBtn. It appears the mf6 vars need to be loaded differently in setmodflowvars().

Getting the vars with mf.nper, mf.dis.ncol.get_data(), etc works. But is there is no "thickness" variable (as there is in modflow.mfdis). Is there another way?

**Comment by emorway-usgs** [comment]
@wkitlasten to clarify, are you attempting to set some of the BTN variables using the flow model object, something similar to the last argument in the following example, and it isn't working when the `mf` object is MODFLOW6?:
```
mt = flopy.mt3d.Mt3dms(modelname=modelname_mt, model_ws=model_ws, 
                       exe_name=exe_name_mt, modflowmodel=mf)
```

**Comment by wkitlasten** [comment]
Yes, I am not trying to set the variables themselves, but I am trying to
have them inherited from the modflowmodel object, which is mf6.

I suppose I can set them manually... or maybe make an "old modflow" object
from the mf6 object? Or is there an mf6 object similar to the modflowmodel
object?

Sent from my phone without spell checker. Please excuse my fat thumbs and
bad eyes.

**Comment by emorway-usgs** [comment]
@wkitlasten The most expedient means forward would be either of the two options you mention.  In the tests I was running, I was comparing MT3D-USGS solutions using (1) mf2k5 and (2) mf6.  In having a 2nd look at what I did, it looks like I set the `dz` variable through the command I mentioned previously, namely:
```
mt = flopy.mt3d.Mt3dms(modelname=modelname_mt, model_ws=model_ws, 
                       exe_name=exe_name_mt, modflowmodel=mf)
```
and I could do it that way because the two flow models on which the mt3d model object was based  were identical, so I could just pass the mf2k5 version of the `mf` object.

This is a bug and something I'll need to work on.  If you have your layer elevations as 2D numpy arrays, you could create a list of 2D layer thicknesses using the elevation arrays and pass the thicknesses to the BTN constructor's `dz` argument.  Something like:

`btn = flopy.mt3dms.Mt3dBtn(mt, ..., dz=[dz_1, dz_2, dz_x], ...)`

This will be the quickest way forward for you, I think.  Thanks for bringing this to my attention.

**Comment by wkitlasten** [comment]
Thanks for responding. I thought about digging deeper into a flopy solution
last night, but bailed. I'm sure I can do an external work around when I
get some time.

Sent from my phone without spell checker. Please excuse my fat thumbs and
bad eyes.

**Comment by emorway-usgs** [comment]
This goes along with #775

**Comment by jdhughes-usgs** [comment]
We implemented a consistent thickness method in the modelgrid object. See  #1138 

Reopen if this does not address the issue.
