### ISSUE TITLE
UZF1 option block not being written

### ISSUE THREAD

**Issue by wkitlasten** [modflowpy/flopy#942]
This causes the model to fail when using newer options like ETSQUARE. Example below:

import flopy
import numpy as np
print('flopy version: {}'.format(flopy.__version__))

modelname = 'uzf_test'
mfexe = 'mfnwt.exe'
mf = flopy.modflow.Modflow(modelname=modelname, exe_name=mfexe, version='mfnwt')
nwt = flopy.modflow.ModflowNwt(mf)

dis = flopy.modflow.ModflowDis(mf) 
bas=flopy.modflow.ModflowBas(mf)

upw = flopy.modflow.ModflowUpw(mf)

#uzf package uses legacy format
#does not write OPTIONS block, so doesn't work with new ETSQUARE option
uzf=flopy.modflow.ModflowUzf1(mf,iuzfopt=1,ietflg=1,etsquare=0.1)

mf.write_input()
mf.run_model()

**Comment by emorway-usgs** [comment]
@jlarsen-usgs In looking at this a bit further, I can trace the origin of this bug to line 327 in optionblock.py.  `self.block` is `False` which directs flopy to write the options as a single line :

![block](https://user-images.githubusercontent.com/3236576/87690304-245a0300-c73e-11ea-8c80-cea353bdb342.png)

At the moment, it looks like the variable `self.block` is hard-wired to `False` on line 480 in mfuzf1.py, which instantiates the optionsblock class:

![2020-07-16_08-22-54](https://user-images.githubusercontent.com/3236576/87690615-861a6d00-c73e-11ea-8eb4-cd1ab9d038d2.png)

As a test, I tried setting `block=True` in the line above, and all worked as expected.  I would submit a PR for this, but because of potential backward compatibility issues, I'm not sure if switching this flag would raise other issues?

**Comment by jlarsen-usgs** [comment]
@emorway-usgs, @wkitlasten 

The code is currently set up that way to prevent using the block style with mf-2005 versions of UZF. There are a couple things that could be done. 1) I could put in a version check on line 480: 
```
if self.parent.version = 'mfnwt':
    block=True
```

2) Until I put in the PR, the user can manually set the block Flag to True by using:

```
uzf=flopy.modflow.ModflowUzf1(mf,iuzfopt=1,ietflg=1,etsquare=0.1)
uzf.options.block = True
```

**Comment by emorway-usgs** [comment]
@jlarsen-usgs I like option 1, but I wonder if the gate-keepers do?  I wonder if they might instead prefer the user to implement your 2nd option.  In any event, thanks for providing a path forward for @wkitlasten

**Comment by wkitlasten** [comment]
My vote is for option 1. Thanks gor the solutions.

Sent from my phone without spell checker. Please excuse my fat thumbs and
bad eyes.
