### ISSUE TITLE
Issues with gridintersect for structured grid

### ISSUE THREAD

**Issue by tomvansteijn** [modflowpy/flopy#995]
I ran into some issues using gridintersect for a structured grid and a large polyline dataset.

- the `transform` function is seemingly called on X,Y of the first and second point of each vertex instead of two arrays of X and Y coordinates. This seems incorrect. see: https://github.com/modflowpy/flopy/blob/0e380bcc55f25e5401a901a81312e546affd0e70/flopy/utils/gridintersect.py#L725-L732
- when processing multilinestring, the `rotate` function is called on a list of geometries instead of a geometry. This seems to fail. The function should iterate over each geometry in the list and perform rotation and translation. See:
https://github.com/modflowpy/flopy/blob/0e380bcc55f25e5401a901a81312e546affd0e70/flopy/utils/gridintersect.py#L734-L736
- the `_check_adjacent_cells_intersecting_line` method fails when intersection produces a GeometryCollection instead of a MultiLineString. GeometryCollection is a composite geometry with the `geoms` attribute, and should be processed similar to a MultiLineString. More generally this function should check for the presence of the `geoms` attribute.
https://github.com/modflowpy/flopy/blob/0e380bcc55f25e5401a901a81312e546affd0e70/flopy/utils/gridintersect.py#L975-L981

Can do a PR with quick fixes if desirable.

**Comment by dbrakenhoff** [comment]
Hey Tom, thanks for submitting these issues! It is very much appreciated if you want to submit a PR with fixes! I'll take a look after you've submitted it!

On a more general note, I haven't tested the structured methods as extensively as the vertex methods because the "vertex" methods outperform structured in most cases. I did some tests with different input shapes and grid sizes and came up with the following results. `strtree` is the current implementation of the `vertex` method and structured is the current `structured` method. Only for point shapes or large grids with input shapes for which the STRtree-query cannot limit the search space by much, the structured method is faster. Though that does not take into consideration the time it takes to build the STRtree. 

![image](https://user-images.githubusercontent.com/6552225/94246499-1c77c580-ff1c-11ea-8b8f-aacfc154e4db.png)

Just figured I'd mention that 'vertex' might be faster, even for structured grids! (Though your case might still fall into that small category for which it isn't.). Anyway, thanks for testing and taking the time to submit this issue!

**Comment by tomvansteijn** [comment]
Thanks! So far I have only tried the structured method, I figured it would be faster.
